### PR TITLE
Early Tx termination

### PR DESCRIPTION
**Pull request by drowe67**
The last few 100ms of Tx audio tends to be cut off when we transition from Tx to Rx.

### CODE REVIEW

**Comment by drowe67** [comment]
@timw thinking about the way the signals flow, and where the latency is:

Mic -> Mic input FIFO A - > TxRx thread -> modulated Tx FIFO B -> sound card output C to Rig Mic

I'm assuming the operating system sound card driver and Rig latency C is small and can be ignored.  So I think we actually have a delay in A & B.  When we press PTT to end the over, there may be unprocessed mic audio samples in A.

So how about this design:
1. On press PTT to Tx-->Rx, we set `endingTx=true`, and sample the current value of `g_outfifo1_empty`. We then wait on `g_outfifo1_empty` changing in a sleep(20) while loop (or we could use the syncronisation objects as per the current design).
2. The thread filling A monitors `endingTx` and stops writing samples.
3. The existing samples in A flow through the TxRx thread into B until A empties.
4. B eventually empties after all the samples have been processed and output.  It then increments `g_outfifo1_empty`
5. The while loop/sync object in step (1) falls out and we tell Hamlib to take the rig out of Tx.

**Comment by tmiw** [comment]
@drowe67, I added step 2 above to the current PR and it looks like that covered pretty much all the remaining audio that was truncated. I think there's still about ~20ms cut off but that seems within limits given what I understand about how my HL2 (and similar SDRs) work. Feel free to give it a try and let me know how it goes.

**Comment by drowe67** [comment]
@tmiw - thanks.  I have an idea for a simpler implementation that I will try out in another branch in a few days so I don't mess this one up!  Will get back to you once I know if it works .... :slightly_smiling_face:

**Comment by drowe67** [comment]
Alternate implementation based on this design  used in https://github.com/drowe67/freedv-gui/pull/123

**Pull request closed without merging**
