### PR TITLE
Refactor configuration handling in the codebase

### PR DESCRIPTION
**Pull request by tmiw**
This PR refactors configuration handling into a separate FreeDVConfiguration class. (Currently loading and saving configuration happens in multiple places in the codebase.) This is a prerequisite before we can implement new functionality (such as customizing the frequency list).

Note: this is still WIP.

### CODE REVIEW

**Comment by Tyrbiter** [comment]
FYI I have built 405467f using ./build_linux.sh pulseaudio and the build completed.

Once you think it's a the point where testing makes sense I will create rpms and try it out for daily use.

**Comment by tmiw** [comment]
> FYI I have built [405467f](https://github.com/drowe67/freedv-gui/commit/405467fc8771c46efdbe83d34eab91ca4ba00d7f) using ./build_linux.sh pulseaudio and the build completed.
> 
> Once you think it's a the point where testing makes sense I will create rpms and try it out for daily use.

Will do.

BTW this seems like a bigger change than anticipated, so I'm considering deferring this until 1.8.13 or 1.9.x. That said, so far, everything seems to be loading and saving fine.

**Comment by tmiw** [comment]
@Tyrbiter This should be good to get a bit more testing now. 👍

**Comment by Tyrbiter** [comment]
> @Tyrbiter This should be good to get a bit more testing now. +1

OK, I will see if I can merge all the branches in (including the new ones I see today) and get it working. I like to have all the changes in if possible.

Will report back but I expect it will take a good few hours to merge all this.

**Comment by Tyrbiter** [comment]
Pulled latest git, then ran ./build_linux.sh pulseaudio and got this error:

[ 38%] Building CXX object src/config/CMakeFiles/fdv_config.dir/FreeDVConfiguration.cpp.o
cd /home/bdm/git/freedv-gui-ms-refactor-config/build_linux/src/config && /usr/lib64/ccache/c++ -DAUDIO_ENGINE_PULSEAUDIO_ENABLE -DGIT_HASH=\"f36923d\" -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -I/home/bdm/git/freedv-gui-ms-refactor-config/build_linux -I/home/bdm/git/freedv-gui-ms-refactor-config/build_linux/sioclient_src/src -I/home/bdm/git/freedv-gui-ms-refactor-config/codec2/src -I/home/bdm/git/freedv-gui-ms-refactor-config/codec2/build_linux -I/home/bdm/git/freedv-gui-ms-refactor-config/src/config/.. -I/home/bdm/git/freedv-gui-ms-refactor-config/build_linux/src/config/.. -isystem /usr/lib64/wx/include/gtk3-unicode-3.0 -isystem /usr/include/wx-3.0 -Wall -pthread -g -std=c++14 -MD -MT src/config/CMakeFiles/fdv_config.dir/FreeDVConfiguration.cpp.o -MF CMakeFiles/fdv_config.dir/FreeDVConfiguration.cpp.o.d -o CMakeFiles/fdv_config.dir/FreeDVConfiguration.cpp.o -c /home/bdm/git/freedv-gui-ms-refactor-config/src/config/FreeDVConfiguration.cpp
In file included from /home/bdm/git/freedv-gui-ms-refactor-config/src/config/FreeDVConfiguration.h:30,
                 from /home/bdm/git/freedv-gui-ms-refactor-config/src/config/FreeDVConfiguration.cpp:25:
/home/bdm/git/freedv-gui-ms-refactor-config/src/config/ReportingConfiguration.h:43:30: error: ‘uint64_t’ was not declared in this scope
   43 |     ConfigurationDataElement<uint64_t> reportingFrequency;
      |                              ^~~~~~~~
/home/bdm/git/freedv-gui-ms-refactor-config/src/config/ReportingConfiguration.h:1:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
  +++ |+#include <cstdint>
    1 | //==========================================================================
/home/bdm/git/freedv-gui-ms-refactor-config/src/config/ReportingConfiguration.h:43:38: error: template argument 1 is invalid
   43 |     ConfigurationDataElement<uint64_t> reportingFrequency;
      |                                      ^
make[2]: *** [src/config/CMakeFiles/fdv_config.dir/build.make:104: src/config/CMakeFiles/fdv_config.dir/FreeDVConfiguration.cpp.o] Error 1
make[2]: Leaving directory '/home/bdm/git/freedv-gui-ms-refactor-config/build_linux'
make[1]: *** [CMakeFiles/Makefile2:290: src/config/CMakeFiles/fdv_config.dir/all] Error 2
make[1]: Leaving directory '/home/bdm/git/freedv-gui-ms-refactor-config/build_linux'
make: *** [Makefile:156: all] Error 2

**Comment by Tyrbiter** [comment]
I have now got a build running that in theory has all 5 currently outstanding PRs merged in, I will keep running it and see if anything breaks, but the config options all seem to have remained set up as they were previously.

**Comment by tmiw** [comment]
BTW #460 is basically going to be the next test build, so you can go ahead and pull/compile that instead of manually merging all open PRs. (#460 includes the code in #457 plus the stuff needed to modify the frequency list.)

**Pull request merged**
