### PR TITLE
Final tidying up before official 1.6.1 release.

### PR DESCRIPTION
**Pull request by tmiw**
Updates:

* Ensure that memory used by PSK Reporter is freed on window close.
* Documentation/CMakeLists updates to reflect new release.

### CODE REVIEW

**Comment by tmiw** [comment]
Let's wait till #169 gets merged before we merge this one.

**Comment by tmiw** [comment]
Once the other two PRs are merged, this can be merged too. 👍

**Comment by tmiw** [comment]
1.6.1 now official: https://github.com/drowe67/freedv-gui/releases/tag/v1.6.1

**Comment by drowe67** [comment]
Well done @tmiw :smile:

**Pull request merged**
