### PR TITLE
Windows installer improvements

### LINKED ISSUE #14: Uninstall should remove configuration
Registry entries on Windows, ~/.FreeDV on Linux

### PR DESCRIPTION
**Pull request by tmiw**
Contains the following changes:

1. Have uninstaller remove Registry key (resolves #14).
2. Include sample .wav files as part of the Windows installation.

### CODE REVIEW

**Comment by drowe67** [comment]
Looks good @tmiw.  Is the location of the demo wave files easy to find for the end user?  I'm wondering if that needs a note in the manual?

**Comment by tmiw** [comment]
> Looks good @tmiw. Is the location of the demo wave files easy to find for the end user? I'm wondering if that needs a note in the manual?

That might be nice. I should test on Linux as well and make sure it installs them somewhere reasonable (e.g. /usr/share/freedv-gui/wav).

**Comment by tmiw** [comment]
I did some more testing and updated CMakeLists.txt and the user manual accordingly. 👍

**Comment by drowe67** [comment]
Looks good @tmiw, feel free to merge when you're ready :slightly_smiling_face:

**Pull request merged**
