### PR TITLE
Use CPack (part of CMake) to generate Debian packages.

### PR DESCRIPTION
**Pull request by tmiw**
Removed broken debian folder/configuration in FreeDV tree and replaced with CPack to automatically generate packages.

@drowe67, it looks like it installs the generated package fine on my Ubuntu VM. Since I didn't specify LPCNet or Codec2 as dependencies, though, the installed binary won't run. I'll create PRs for those two projects shortly and update dependencies here too.

### CODE REVIEW

**Comment by drowe67** [comment]
@tmiw OK that's pretty cool.  So are these packages for Ubuntu as well as Debian?

IIRC the Debian files might have been there for an upstream type reason.  Lets see if we can find Maitland (AA4HS) and get him to review (I had a hard drive die so have lost a lot of emails addresses).

@hobbes1069 - do you have any thoughts on this Ubuntu packaging?

**Comment by tmiw** [comment]
@drowe67, they should be. I made sure to set the minimum version numbers such that the same packages _should_ install on both.

Unfortunately, after installing all three packages, I get the following error:

```
mooneer@ubuntu:~/freedv-gui/LPCNet$ freedv
freedv: symbol lookup error: freedv: undefined symbol: freedv_get_hash
mooneer@ubuntu:~/freedv-gui/LPCNet$
```

Which seems weird since ldd seems to correctly indicate LPCNet and Codec2:

```
mooneer@ubuntu:~/freedv-gui/LPCNet$ ldd /usr/bin/freedv
...
	libcodec2.so.0.9 => /usr/lib/x86_64-linux-gnu/libcodec2.so.0.9 (0x00007fbfc3642000)
	liblpcnetfreedv.so.0.2 => /usr/lib/liblpcnetfreedv.so.0.2 (0x00007fbfc28d3000)
...
mooneer@ubuntu:~/freedv-gui/LPCNet$
```

Maybe others can try and see if they see the same?

**Comment by drowe67** [comment]
@tmiw some recent contact info for AA4HS https://wiki.debian.org/DebianHams.  Lets see if we can reach out to him and get a comment on this series of PRs.

**Comment by tmiw** [comment]
@drowe67, I don't see any email for him (on the page you linked or on QRZ) other than the debian-hams mailing list. However, there is an IRC channel, so maybe we can join that and see if he's there?

**Comment by drowe67** [comment]
@tmiw I've just tried that Debian list email, can you pls try IRC?

**Comment by tmiw** [comment]
@drowe67, I joined and left the question in the channel; I'll check for a response after work.

**Comment by tmiw** [comment]
@drowe67, so there might have been a misunderstanding but the response I got sounded like we may need to keep the existing debian/ folder and configuration (something about the team using dpkg-buildpackage). I'll wait until you hear back as well before I begin backing out deletions.

**Comment by tmiw** [comment]
@maitbot, thanks for the comments. I don't foresee CPack interfering with whatever distributions decide to do to perform their packaging, so we should be good there. CPack should allow us to provide test builds for users if they so choose, before releases are made official.

@drowe67, looks like I had libcodec2 packages in my VM which were getting loaded instead of the ones in the .deb files I was generating, hence the load error. I removed the libcodec2 packages and the packages I generated started to work with no issues.

**Comment by drowe67** [comment]
> @maitbot, thanks for the comments. I don't foresee CPack interfering with whatever distributions decide to do to perform their packaging, so we should be good there. CPack should allow us to provide test builds for users if they so choose, before releases are made official.

@tmiw as @maitbot suggests - is the use of CPack optional (e.g. a separate `make` target)?  Can you pls add instructions to freedv-gui/README.md for building a FreeDV CPacks?

**Comment by drowe67** [comment]
Thanks @maitbot. 

On a related note - from time to time we get requests from distro maintainers for work - some of it quite significant in terms of man hours.  One question I've asked @hobbes1069 (who maintains Fedora) is - do you have any evidence/records to estimate of are any people actually using FreeDV in your distro, for example logs or other feedback?

**Comment by tmiw** [comment]
> @tmiw as @maitbot suggests - is the use of CPack optional (e.g. a separate `make` target)? Can you pls add instructions to freedv-gui/README.md for building a FreeDV CPack?

Yes. To generate the Debian packages, simply run "cpack" after running "make".

**Comment by drowe67** [comment]
Nice work @tmiw :+1:

**Pull request merged**
