### PR TITLE
Add Record button on the main page.

### PR DESCRIPTION
**Pull request by tmiw**
Per request mentioned in #368, this PR adds a record button on the main window to make it faster to kick off a recording from the radio.

### CODE REVIEW

**Comment by Tyrbiter** [comment]
OK, built and tested, appears to work in that I have some .wav files in my home directory.

I will report further once I have managed to record some actual freedv signals :)

**Comment by tmiw** [comment]
> One suggestion, when this is revisited would it be sensible to move the record button nearer to the Control buttons? Or maybe add a keyboard accelerator?

Maybe. I'll probably release a test build soon with this feature and see if there are any suggestions on placement.

**Comment by Tyrbiter** [comment]
I have built and am testing these latest changes.

Had an idea: the callsign panel is blank once a signal has disappeared, so add a small indicator that the callsign list contains entries.

**Comment by tmiw** [comment]
> Had an idea: the callsign panel is blank once a signal has disappeared, so add a small indicator that the callsign list contains entries.

Any ideas on what that should look like?

**Comment by tmiw** [comment]
> I'm not familiar with what wxWidgets offers, but perhaps just a numeric count to the right of the drop down arrow, blanked when it's 0.

I think disabling the combo box may provide sufficient indication. See https://github.com/drowe67/freedv-gui/pull/378.

**Comment by Tyrbiter** [comment]
That's a far more elegant suggestion, award yourself a gold star

**Comment by Tyrbiter** [comment]
Record filename string is truncated in the main window, not sure why as window is wide enough for it:

Screenshot from 2023-04-25 18-40-41

**Comment by tmiw** [comment]
> Record filename string is truncated in the main window, not sure why as window is wide enough for it:

Thanks! This has been fixed in https://github.com/drowe67/freedv-gui/pull/379.

**Comment by Tyrbiter** [comment]
One thing I have noticed, when the recording is ended the audio sent to the playback device is stopped until the OK button is clicked in the dialog.

**Comment by tmiw** [comment]
> One thing I have noticed, when the recording is ended the audio sent to the playback device is stopped until the OK button is clicked in the dialog.

The waterfall definitely stops until you push OK but I don't recall the audio stopping as well (though I could be remembering wrong). The latter isn't ideal for sure.

Anyway, now that the status bar is working properly, perhaps the dialog boxes aren't actually necessary? People can still get feedback by either looking there or checking the Tools menu.

**Pull request merged**
