### PR TITLE
Install user manual along with executable

### PR DESCRIPTION
**Pull request by tmiw**
Installs the user manual alongside the executable per comments in https://github.com/drowe67/freedv-gui/issues/185.

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, not sure if there's a cross platform way of opening web pages so not sure about option 3 in the original comment yet. Suggestions appreciated for sure.

**Comment by drowe67** [comment]
Hi @tmiw - I'm sorry I thought I had commented on this one, but perhaps I didn't press the Comment button - Ooops!

This WxWidgets control might be useful for hyperlinks: https://docs.wxwidgets.org/trunk/classwx_hyperlink_ctrl.html.

However I think the key issue here is to alert first time users that a manual exists.  After that it's pretty easy to find (e.g. Google, freedv.org), even if we don't have it hyperlinked.  The natural place to look is the Help Menu.  So perhaps we could:
1. Add some text to the Help-About dialog "see on line FreeDV Manual for extensive help".
1. Add a Help-Manual option.
1. We could add a short URL link e.g. freedv.org#manual that's easy to type in even if it's not a hyperlink.

**Comment by tmiw** [comment]
Turns out there's a built-in wxWidgets function for opening the browser. Added "User Manual" to the Help menu.

**Comment by drowe67** [comment]
Thanks @tmiw that's great :smile: For a new user it's quite natural to look at the Help menu, and the manual option is now very obvious.  Feel free to merge and close #185 if you are happy.

**Pull request merged**
