### PR TITLE
Suppress unnecessary rig_init in hamlib.

### PR DESCRIPTION
**Pull request by tmiw**
Per #172, this only calls rig_init() if the user changes the radio type or on first start.

@drowe67, @Tyrbiter, let me know if this looks okay.

### CODE REVIEW

**Comment by drowe67** [comment]
Looks good to me @tmiw :+1: It would be good to test this change with a wider audience as part of the next beta, PTT has been a tricky area in the past

**Comment by tmiw** [comment]
I'll generate a new test build tonight containing this and #169. Then if good, we can merge all three pending PRs and generate a final 1.6.1 build.

**Comment by tmiw** [comment]
Just to confirm, this is with https://github.com/Hamlib/Hamlib/issues/797 applied too, right? If I understood the discussion thread correctly, this PR + that patch should have done the trick (although the VFO will still switch to VFO A on first start, just suppressing it on future starts while the app is open).

Anyway, I'd rather not have FreeDV always keep Hamlib connected as that's a more significant design change.

**Comment by tmiw** [comment]
BTW, I just emailed out [the RC build](https://www.dropbox.com/sh/gfrszhss1htpzux/AABqezaHdni9yYJjrRHMkOeDa?dl=0) (based on #168 which contains all current open PRs).

**Comment by Tyrbiter** [comment]
No, I was using the released hamlib-4.3.1, so I will correct that mistake and report back.

**Comment by Tyrbiter** [comment]
I'm with @drowe67 regarding the trickiness of this, so I don't want to hold up the new release and risk breaking this area of the program.

Thinking cap back on...

**Comment by tmiw** [comment]
I haven't heard of any issues with the test build, so we can probably merge this now.

**Pull request merged**
