### PR TITLE
Update frequency display

### PR DESCRIPTION
**Pull request by uweham**
i have add a timer (15 sec) to update the frequency display, see #265

### CODE REVIEW

**Comment by tmiw** [comment]
@uweham, thanks for the pull request! Can you add a changelog entry to USER_MANUAL.md for this PR?

@Tyrbiter, can you run the code in this PR when you have a chance and let me know if it helps with #212 at all?

**Comment by Tyrbiter** [comment]
OK, well I can see the frequency and mode debug from hamlib every 15s, so the timer is working and calling the correct function.

However the mode display is still showing red when I select VFO A which is 7.177MHz LSB having started freedv with VFO B 14.236, so something needs to trigger a re-check of the mode detection logic with this timer.

**Comment by uweham** [comment]
@Tyrbiter
 i have tried to reproduce the problem. I have a FT818 rig where in Digimode USB/LSB must be set manually each time (USER-L or USER-U DIG Mode).
When switching VFO A/B, I then always see LSB when USER-L is enabled, regardless of frequency. 
If I switch the trx to talk mode LSB/USB, then LSB/USB is displayed correctly when switching VFO A/B and it is not red.
VFO A 7.177 LSB : black 
VFO B 14.236 USB : black
The method of determining the color is in hamlib.cpp ( Hamlib::update_mode_status() ) Can you debug these method ?

**Comment by tmiw** [comment]
Perhaps try updating `update_frequency_and_mode()` like so?

```
int Hamlib::update_frequency_and_mode(void)
{
    if (m_rig == nullptr)
    {
        return RIG_EARG; // "NULL RIG handle or any invalid pointer parameter in get arg"
    }
    
    rmode_t mode = RIG_MODE_NONE;
    pbwidth_t passband = 0;
    vfo_t currVfo = RIG_VFO_A;
    int result = rig_get_vfo(m_rig, &currVfo);
    if (result != RIG_OK)
    {
        if (g_verbose) fprintf(stderr, "rig_get_vfo: error = %s \n", rigerror(result));
    }
    else
    {
        result = rig_get_mode(m_rig, currVfo, &mode, &passband);
        if (result != RIG_OK)
        {
            if (g_verbose) fprintf(stderr, "rig_get_mode: error = %s \n", rigerror(result));
        }
        else
        {
            freq_t freq = 0;
            result = rig_get_freq(m_rig, currVfo, &freq);
            if (result != RIG_OK)
            {
                if (g_verbose) fprintf(stderr, "rig_get_freq: error = %s \n", rigerror(result));
            }
            else
            {
                m_currMode = mode;
                m_currFreq = freq;
                update_mode_status();
            }
        }
    }

    return result;
}
```

(One would think RIG_VFO_CURR would do the same thing, but I guess not.)

**Comment by Tyrbiter** [comment]
https://github.com/drowe67/freedv-gui/pull/266#issuecomment-1210982193

Just tried this and it seems to work for me, I now get the correct USB/LSB indication on VFO change. Changing mode also correctly shows the mode in red when it is incorrect.

I will see if I find any unexpected things happening and report if I do.

**Comment by tmiw** [comment]
> [#266 (comment)](https://github.com/drowe67/freedv-gui/pull/266#issuecomment-1210982193)
> 
> Just tried this and it seems to work for me, I now get the correct USB/LSB indication on VFO change. Changing mode also correctly shows the mode in red when it is incorrect.
> 
> I will see if I find any unexpected things happening and report if I do.

Sounds good.

@uweham, I wonder if 5 seconds would work just as well or if it'll cause problems. Might be something to try before merge.

**Comment by Tyrbiter** [comment]
I see a lot of this in the debug output:

read_string_generic: port_read is busy? direct=1

seems to happen during the hamlib calls

Is this freedv code or hamlib?

**Comment by tmiw** [comment]
> I see a lot of this in the debug output:
> 
> read_string_generic: port_read is busy? direct=1
> 
> seems to happen during the hamlib calls
> 
> Is this freedv code or hamlib? I'm guessing hamlib.

Yep, hamlib.

**Comment by tmiw** [comment]
I did some brief testing and 5 seconds seemed to work okay (piHPSDR connected via TCP/IP to a Hermes Lite 2). Let me know if that causes issues for you guys.

**Comment by Tyrbiter** [comment]
Built and installed a version with these new changes. Will let you know, so far it seems to work well and of course quicker change of display.

Asking the hamlib list about the debug, it's not a freedv problem.

**Comment by Tyrbiter** [comment]
There is a brief pause in the spectrum and waterfall when the 5 second timer triggers, perhaps this should be run in a separate thread?

**Comment by uweham** [comment]
I think the time to response of hamlib depends on the trx and is not deterministic. I don't know what kind of effort it is to outsource the update function into a separate thread :-( 
A quick workaround would be the update in larger intervals (15 sec, 30 sec ?? )

**Comment by Tyrbiter** [comment]
> I think the time to response of hamlib depends on the trx and is not deterministic. I don't know what kind of effort it is to outsource the update function into a separate thread :-( A quick workaround would be the update in larger intervals (15 sec, 30 sec ?? )

I expect @tmiw will know the answer, I think 5s is about right but like you I don't know how to make this happen in a separate thread.

**Comment by tmiw** [comment]
> > I think the time to response of hamlib depends on the trx and is not deterministic. I don't know what kind of effort it is to outsource the update function into a separate thread :-( A quick workaround would be the update in larger intervals (15 sec, 30 sec ?? )
> 
> I expect @tmiw will know the answer, I think 5s is about right but like you I don't know how to make this happen in a separate thread.
> 
> Looking at this again with a 700E decode running in the spectrum window it is only the spectrum plot that hesitates, the codec2 and audio process does not seem to.

Try the latest commit and see if that helps?

**Comment by Tyrbiter** [comment]
Thanks @tmiw, quite a big commit :-0, unfortunately I get this when I try and build:

In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/plot_scalar.cpp:23:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:163: src/CMakeFiles/freedv.dir/plot_scalar.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_options.h:25,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_options.cpp:22:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:107: src/CMakeFiles/freedv.dir/dlg_options.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_filter.h:25,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_filter.cpp:21:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:93: src/CMakeFiles/freedv.dir/dlg_filter.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:88,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:25,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.cpp:22:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:121: src/CMakeFiles/freedv.dir/dlg_ptt.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_audiooptions.cpp:22:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:79: src/CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/plot_waterfall.cpp:24:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:205: src/CMakeFiles/freedv.dir/plot_waterfall.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/plot_spectrum.cpp:24:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:191: src/CMakeFiles/freedv.dir/plot_spectrum.cpp.o] Error 1
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/dlg_ptt.h:26,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:75,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.cpp:27:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:58:14: error: 'condition_variable' in namespace 'std' does not name a type
   58 |         std::condition_variable statusUpdateCV_;
      |              ^~~~~~~~~~~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::condition_variable' is defined in header '<condition_variable>'; did you forget to '#include <condition_variable>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <condition_variable>
   11 | }
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:59:14: error: 'mutex' in namespace 'std' does not name a type
   59 |         std::mutex statusUpdateMutex_;
      |              ^~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/hamlib.h:11:1: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
   10 | #include <hamlib/rig.h>
  +++ |+#include <mutex>
   11 | }
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:135: src/CMakeFiles/freedv.dir/main.cpp.o] Error 1
gmake[2]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:201: src/CMakeFiles/freedv.dir/all] Error 2
gmake[1]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build'
gmake: *** [Makefile:159: all] Error 2

**Comment by tmiw** [comment]
> Thanks @tmiw, quite a big commit :-0, unfortunately I get this when I try and build:


Oops, try now?

**Comment by Tyrbiter** [comment]
Got further, but now this:

[ 98%] Building CXX object src/CMakeFiles/freedv.dir/freedv_interface.cpp.o
cd /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build/src && /usr/lib64/ccache/g++ -DAUDIO_ENGINE_PULSEAUDIO_ENABLE -DGIT_HASH=\"None\" -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D__WXGTK__ -I/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src -I/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build/src -I/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build -isystem /usr/lib64/wx/include/gtk3-unicode-3.0 -isystem /usr/include/wx-3.0 -isystem /usr/include/codec2 -isystem /usr/include/lpcnet -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -pie -Wl,-z,relro -Wl,-z,now -Wall -pthread -O2 -g -DNDEBUG -std=c++14 -MD -MT src/CMakeFiles/freedv.dir/freedv_interface.cpp.o -MF CMakeFiles/freedv.dir/freedv_interface.cpp.o.d -o CMakeFiles/freedv.dir/freedv_interface.cpp.o -c /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/freedv_interface.cpp
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/ongui.cpp:524:6: error: no declaration matches 'void MainFrame::resetStats_()'
  524 | void MainFrame::resetStats_()
      |      ^~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/ongui.cpp:524:6: note: no functions named 'void MainFrame::resetStats_()'
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/ongui.cpp:7:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/main.h:397:7: note: 'class MainFrame' defined here
  397 | class MainFrame : public TopFrame
      |       ^~~~~~~~~
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/ongui.cpp: In member function 'virtual void MainFrame::OnBerReset(wxCommandEvent&)':
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/src/ongui.cpp:541:5: error: 'resetStats_' was not declared in this scope
  541 |     resetStats_();
      |     ^~~~~~~~~~~
gmake[2]: *** [src/CMakeFiles/freedv.dir/build.make:359: src/CMakeFiles/freedv.dir/ongui.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:201: src/CMakeFiles/freedv.dir/all] Error 2
gmake[1]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.3/redhat-linux-build'
gmake: *** [Makefile:159: all] Error 2
error: Bad exit status from /home/bdm/rpmbuild/tmp/rpm-tmp.XClkdD (%build)

**Comment by tmiw** [comment]
> Got further, but now this:

Just tried building on Ubuntu 22.04 in case it was something Clang on my Mac was doing and had no issues. Maybe re-clone the repo just in case there's something sticking around that shouldn't be?

**Comment by Tyrbiter** [comment]
My fault, my local build included PR #262 so I needed to incorporate that too, everything built properly this time.

However, the result is that the change of threading now doesn't seem to call hamlib at all once the modem is running, so it looks like it's broken. Quite a complex change so I'm not surprised.

**Comment by tmiw** [comment]
I'm currently testing with SmartSDR (Flex 6300) and it seems to be updating as appropriate while receiving. However, that doesn't rule out issues on radios with a physical USB or serial connection, so maybe more testing is needed on my end.

**Comment by tmiw** [comment]
Actually, try the latest. I was attempting to suppress updates during TX but perhaps that's not actually necessary and could be causing problems.

**Comment by Tyrbiter** [comment]
> Actually, try the latest. I was attempting to suppress updates during TX but perhaps that's not actually necessary and could be causing problems.

That seems to be working nicely, for some reason it has also got rid of the excessive hamlib debug I mentioned previously too.

That seems like a win.

Not sure about the updates during Tx. Some radios won't like doing that but I think it's down to hamlib to play referee on this.

**Comment by uweham** [comment]
I'm currently using an FT818 rig and the latest did not work for me 

update freq and mode ....
rig_get_vfo called
rig_get_vfo: no get_vfo
rig_get_vfo: error = Feature not available 

when i press <Start> the first display are correct. The log 

starting tx/rx processing thread
rig: Yaesu FT-818 (1041)
rig_init called
ft817_init: called, version 20200710.0
rig_init() OK ....
hamlib: ignoring CI-V configuration due to non-Icom radio
hamlib: setting serial rate: 9600
hamlib: serial rate: 9600
hamlib: data_bits..: 8
hamlib: stop_bits..: 2
rig_open called
port_open called
serial_open called
serial_setup called
serial_flush called
tcflush
ft817_open: called 
rig_get_vfo called
rig_get_vfo: no get_vfo
hamlib: rig_open() OK
rig_get_vfo called
rig_get_vfo: no get_vfo
rig_get_vfo: error = Feature not available

**Comment by Tyrbiter** [comment]
It looks like you are using quite an old hamlib, the current hamlib-4.5~git version shows the FT-817 version date as 20220419.0

There has been a lot of development in hamlib and the later versions should work better for you.

**Comment by tmiw** [comment]
Actually, even if it were a hamlib issue I think this PR shouldn't break anything that previously worked.

@uweham, try the latest commit and let us know how that goes?

**Comment by Tyrbiter** [comment]
> Actually, even if it were a hamlib issue I think this PR shouldn't break anything that previously worked.

I agree, although it can be difficult to work out what broke it.

Hamlib 4.5 is again within a day of release but I bet it gets put back again, the result is that all the improvements in it don't make it out into the wider world and some Linux distros are very slow to update packages anyway.

**Comment by uweham** [comment]
@tmiw:  i have try your latest commit, but it do not work, i have look at your commit and look to the hamlib.h:  Hamlib functions return the negative value.
I change that, and then it works for me. (with the old version of hamlib)

**Comment by Tyrbiter** [comment]
In hamlib's rig.h there is the following:

   RIG_ENAVAIL,    /*!< 11 Function not available */

I don't understand why that is a negative response. It's part of an enum list starting at 0 and incrementing for each member.

**Comment by tmiw** [comment]
> In hamlib's rig.h there is the following:
> 
> RIG_ENAVAIL, /*!< 11 Function not available */
> 
> I don't understand why that is a negative response. It's part of an enum list starting at 0 and incrementing for each member.

Everything using that error code in the Hamlib codebase seems to be getting negated before getting returned so it seems to be a standard convention they went with.

**Comment by Tyrbiter** [comment]
> Everything using that error code in the Hamlib codebase seems to be getting negated before getting returned so it seems to be a standard convention they went with.

OK, I didn't realise that, as a non-software engineer I do find a lot of code conventions, macros and defines a bit hard to read and parse.

**Comment by tmiw** [comment]
Did some testing over the last few days and it looks good here, so I'll merge and see if any issues show up in wider use.

**Pull request merged**
