### PR TITLE
Allow dynamic updating of message column width.

### PR DESCRIPTION
**Pull request by tmiw**
Per request in #720, allow contents of message column to dynamically adjust based on the physical column width.

### CODE REVIEW

**Comment by barjac** [comment]
Hi Mooneer,
Yes that's looking good! Very nearly there ;)
Only minor issue is that when dragging out the column width sometimes the ellipsis does not follow it, so you can't tell whether you have reached the end of the message or not.

To reproduce this grab the right hand Msg heading divider and compress the messages so they all have ellipsis.
Now release the left button.
Now grab the divider again and slowly widen the column. The message width increases and then stops, (still with an ellipsis) no matter how wide the divider is taken, until the button is released, when the remainder of the message appears.

**Comment by tmiw** [comment]
> Hi Mooneer, Yes that's looking good! Very nearly there ;) Only minor issue is that when dragging out the column width sometimes the ellipsis does not follow it, so you can't tell whether you have reached the end of the message or not.
> 
> To reproduce this grab the right hand Msg heading divider and compress the messages so they all have ellipsis. Now release the left button. Now grab the divider again and slowly widen the column. The message width increases and then stops, (still with an ellipsis) no matter how wide the divider is taken, until the button is released, when the remainder of the message appears.

Yeah, that was intentional originally since I didn't think it could be adjusted while dragging. Try now?

**Comment by barjac** [comment]
Just came across another issue:
Sometimes if there is a long message with an ellipsis in the column and this is not of interest so the column is not expanded to include it all then even when the cursor is not over that window, the column expands by a few characters at a time every 5 seconds until the whole of the long message is finally displayed.
Not sure exactly how to reproduce reliably but I did get a screen video of the final few steps of it happening.

https://github.com/drowe67/freedv-gui/assets/1324702/a92b8ce7-6d84-4fa8-8815-e9f246cde339

**Comment by tmiw** [comment]
I think it's fixed with the latest change. Try now?

**Comment by barjac** [comment]
Yes that works fine now. :)

Would it be possible to retain the column width when switching between filters?
I am now (with these recent improvements) setting the Msg column width to the max that suits my screen so that I rarely see the ellipsis, however on switching filter or changing band at the radio, it is reset to the default again.

Maybe it could be retained between sessions too if it is not default.

**Comment by tmiw** [comment]
> Would it be possible to retain the column width when switching between filters? I am now (with these recent improvements) setting the Msg column width to the max that suits my screen so that I rarely see the ellipsis, however on switching filter or changing band at the radio, it is reset to the default again.

Yep and done.

> /OT Have fun at the Hamvention! I just watched your EzDV talk :)

\o/

**Comment by barjac** [comment]
Yes that is working as expected now, any chance of:
"Maybe it could be retained between sessions too?"
...if you agree that it would be useful.

**Comment by barjac** [comment]
Just noticed that the Msg column width setting is lost when switching to analogue and back to digital.

**Comment by tmiw** [comment]
> Just noticed that the Msg column width setting is lost when switching to analogue and back to digital.

I just tried on macOS and Linux and that doesn't seem to happen for me. Can you make sure you're running in the latest in the PR?

**Comment by tmiw** [comment]
> Yes that is working as expected now, any chance of: "Maybe it could be retained between sessions too?" ...if you agree that it would be useful.

Done.

**Comment by barjac** [comment]
> Just noticed that the Msg column width setting is lost when switching to analogue and back to digital.

I think I was being confused by the lack of my extra wide 'version' which was not there when  I switched to analogue, on re-test with latest it does in fact work as expected.

**Comment by barjac** [comment]
> > Yes that is working as expected now, any chance of: "Maybe it could be retained between sessions too?" ...if you agree that it would be useful.
> 
> Done.

Yes that's great now. I think this is now ready. :)

I will test again during the UK Sunday RSGB News and following net and let you know if anything else crops up.

**Pull request merged**
