### PR TITLE
Autodetect sound device config changes in FreeDV and notify user

### PR DESCRIPTION
**Pull request by tmiw**
Moving PortAudio changes originally in #77 to a separate PR for further debugging/discussion. Currently, Virtual Audio Cable causes problems with Windows due to how devices are named, so this is a WIP.

### CODE REVIEW

**Comment by tmiw** [comment]
Not sure why the build is erroring, but maybe it'll fix itself once I can go back to this.

Anyway, it looks like the current implementation was translating the two Virtual Audio Cable devices for the radio into the same device ID. Later on, it ends up clearing one of the devices because it's already used. Will have to think more about how to get around that.

**Comment by tmiw** [comment]
So I think the most recent commit actually fixes the issue we were seeing on Windows, but more testing will be needed to be sure. I put a build up [here](https://www.dropbox.com/s/5vz8uelmqnavmqs/FreeDV-1.5.1-devel-20201231-2578d57-win64.exe?dl=0).

**Comment by tmiw** [comment]
@drowe67, so far so good. Walter K5WH is using a build from this PR and hasn't had any issues. I haven't had any issues on Mac, either, so we just need some people test on Linux (and maybe a few more on Windows for good measure).

**Comment by drowe67** [comment]
Well done @tmiw - this will really help people by removing a common and annoying source of errors :+1:

**Comment by drowe67** [comment]
Nice work @tmiw - looks much cleaner now we've merged https://github.com/drowe67/freedv-gui/pull/77 :slightly_smiling_face: 

I suggest we bump the version FreeDV number to 1.5.2 - that will let us distinguish the work in this PR from https://github.com/drowe67/freedv-gui/pull/77.  As I mentioned - we experienced some issues with a year ago so it would be good to have a way to cleanly ID the version should end users run into any problems.

**Comment by tmiw** [comment]
@drowe67, agreed. Version updated to 1.5.2.

**Comment by tmiw** [comment]
@drowe67, I haven't heard any additional feedback on this, so we may be good to go?

**Comment by drowe67** [comment]
@tmiw - this change will affect all FreeDV users, and we have had a few problems with a similar mod in the past.  So I'm OK to merge it, as long as we can show it works fine for a small subset of end users.

Can you pls tell me how many people have tried it and found it to work OK with their configuration?

**Comment by tmiw** [comment]
@drowe67, it's gotten some testing by me as well as Walter K5WH. However, maybe one or two more testers would be good. I've generated builds [here](https://www.dropbox.com/sh/1bp2fmqjcuqltup/AABzsxlmhBGAfWOUFHXmEf6Ca?dl=0) and sent out an email to the digitalvoice list asking for feedback (I thought I had before, but apparently I only sent the Windows build to K5WH).

**Comment by drowe67** [comment]
Thanks @tmiw - I imagine if Walter has tested it, so have many of his friends :slightly_smiling_face:

**Comment by drowe67** [comment]
@tmiw - thanks for that extra testing.  If you feel you're not getting enough test reports I have a few more people we can send it too.  Just let me know.

**Comment by tmiw** [comment]
@drowe67, I haven't heard back (other than that comment about the Debian packages' dependencies), so any additional testers you can send it to would be good. 👍

**Comment by drowe67** [comment]
@tmiw well it's the weekend here.  From the reports I saw during the week:
1.  I didn't hear of any issues with the audio/sound card selection. So I think we are good to merge this PR :+1: 
2. The PSK reporter line update might still need some work.  Is that disabled and the original txt line mode enabled by default?

**Comment by tmiw** [comment]
@drowe67, the PSK Reporter stuff isn't enabled by default. Since this just touched the audio settings stuff, we can merge this PR.

However, it seems that non-PSK Reporter decoding is broken from what I've seen. I should have a chance to investigate further this weekend and see what's going on there.

**Comment by drowe67** [comment]
> @drowe67, the PSK Reporter stuff isn't enabled by default. Since this just touched the audio settings stuff, we can merge this PR.

Will do.

> However, it seems that non-PSK Reporter decoding is broken from what I've seen. I should have a chance to investigate further this weekend and see what's going on there.

Ahh - OK - yes it would be great if we can fix that :+1:

**Comment by tmiw** [comment]
@drowe67, weird, I just merged the current master into my local bugfixes branch and tried decoding the various .wav files with PSK Reporter off. No issues decoding the text field on those. I'm going to assume that it was just a user error on my part until I discover otherwise.

**Comment by drowe67** [comment]
@tmiw Cool.  Did anyone else report problems with PSK reporter off?

**Comment by tmiw** [comment]
@drowe67, not that I've heard. The stuff I heard about text not displaying could just be related to PSK Reporter functionality being on.

**Pull request merged**
