### PR TITLE
Restrict resize to a minimum size that won't cause GTK warnings.

### PR DESCRIPTION
**Pull request by tmiw**
Per #133, here are some tweaks to ensure that the window can't be resized too small (and causing GTK warnings among other isuses).

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, BTW, here's the smallest I can resize the main window with this PR:

Screen Shot 2021-05-27 at 7 40 53 PM

**Comment by drowe67** [comment]
@timw - that's great and works really well, and resolves all of my concerns in https://github.com/drowe67/freedv-gui/issues/133 :grinning: .  Any time I tried to resize - the layout was fine (even after Start was pushed) :+1: 

I even tried the "tiling trick" and it worked Ok:

Screenshot from 2021-05-28 14-57-30

Some super small things that you don't have to tackle in this PR, but I wanted to mention:
1. Occasionally, when I drag the spectrum plot to the top of the centre panel, freedv-gui bombs, I've noticed this occasionally for the last few weeks.  But I can't figure out how to repeat it reliably.
1. When the window is re-sized - the waterfall often gets filled with "noise" - probably some un-initialised screen buffer memory.  Example in the waterfall above.
1. I was trying to figure out how to get the stats numbers  to use a justification other than LH, but I think it's a proportional font, so hard to say RH align them.

**Comment by tmiw** [comment]
Just pushed a change to PR #131 that should help with point 2 above. Center justifying the stats numbers shouldn't be a big deal, I'll work on that in this PR now.

**Comment by drowe67** [comment]
Thanks :slightly_smiling_face: Actually I'm not sure what justification would be best, ie center or right, or perhaps left but with the digits in each field aligned to a new column in the center of the stats window.  Here's one possibility:
```
Bits:         6390
Errs:            8
BER:         0.001
Resyncs:         8
```
or maybe:
```
Bits:        6390
Errs:        8
BER:         0.001
Resyncs:     8
```
:thinking: not sure if that's 100% right either.  Maybe there is a convention for this?

**Comment by tmiw** [comment]
Right now the stats display is one static text field per stat. We'd probably need to split each into two (one for the label, one for the value) to accomplish either of those options. For now, I center aligned each of the existing static text fields, but perhaps another issue/PR would be best for this one.

**Comment by drowe67** [comment]
Hi @tmiw - I reverted the center alignment of the Stats text as I felt it didn't really address the (minor) core issue, as discussed above in https://github.com/drowe67/freedv-gui/pull/135#issuecomment-850263755.

Were there any other changes you wanted to make in this PR, or are we OK to merge?

**Comment by tmiw** [comment]
@drowe67, this is OK to merge.

**Pull request merged**
