### PR TITLE
Auto-size columns in Audio Options based on device names.

### PR DESCRIPTION
**Pull request by tmiw**
Based on feedback, this PR auto-sizes the columns inside the Audio Options window to make longer device names easier to read.

### CODE REVIEW

**Comment by tmiw** [comment]
@barjac, hopefully this works okay for you. 👍

**Comment by barjac** [comment]
Yes, thanks. :)
I agree with Brian that the other columns would benefit from the same treatment.

**Comment by tmiw** [comment]
> Yes, thanks. :) I agree with Brian that the other columns would benefit from the same treatment.

Wait, the code should already be resizing all four columns unless I'm misunderstanding something?

**Comment by barjac** [comment]
Yes exactly, sorry for confusion - I was going from memory.

**Comment by Tyrbiter** [comment]
> > Yes, thanks. :) I agree with Brian that the other columns would benefit from the same treatment.
> 
> Wait, the code should already be resizing all four columns unless I'm misunderstanding something?
> 
> EDIT: oh, Brian meant preserving the size/location of the Audio Options dialog. +1

Yes, I meant that the last 3 columns are effectively hidden so to see them all the window has to be widened, but then when it's closed the same thing happens when it is reopened.

**Pull request merged**
