### PR TITLE
Add tests to verify lack of sync loss in RX

### PR DESCRIPTION
**Pull request by tmiw**
Adds additional ctests to verify that FreeDV does not lose sync during RX.

## Test Setup

* Test systems:
    * macOS: 2019 MacBook Pro (8 core 2.3 GHz Intel Core i9), 64 GB RAM, macOS 15.1
    * Linux: Raspberry Pi 5 (4 core ARM Cortex A76 @ 2.4 GHz), 8 GB RAM, latest Raspberry Pi OS
    * Windows: 
        1. Lenovo IdeaPad Y410P (Intel Core i7-4700MQ, 8 GB RAM, Windows 10)
        2. Intel NUC (Intel Core i3-4010U, 8 GB RAM, Windows 10)
        3. Windows-10,  Intel Core I7-4819MQ 2.8ghz 2801 4 Cores, 8 Logical, 32g of memory (Thanks Walter K5WH)
* "Radio" sound device: Griffin iMic USB sound card with 3.5mm cable between "Mic" and "Speaker" ports.
* "Analog" sound device: 
    * macOS/Windows: Built-in speaker/mic on device
    * Linux: Generic USB sound device, no cables plugged in

### Linux/macOS

```
$ UT_ENABLE=1 ./build_linux.sh (or ./build_osx.sh)
$ cd build_[linux|osx]
$ for i in {1..10}; do FREEDV_COMPUTER_TO_RADIO_DEVICE="[radio device]" FREEDV_RADIO_TO_COMPUTER_DEVICE="[radio device]" FREEDV_COMPUTER_TO_SPEAKER_DEVICE="[analog device]" FREEDV_MICROPHONE_TO_COMPUTER_DEVICE="[analog device]" ctest -R fullduplex; done
```

Example execution from Ubuntu 22.04 aarch64 VM with above hardware:

```
for i in {1..10}; do FREEDV_COMPUTER_TO_RADIO_DEVICE="alsa_output.usb-Griffin_Technology__Inc_iMic_USB_audio_system-00.analog-stereo" FREEDV_RADIO_TO_COMPUTER_DEVICE="alsa_input.usb-Griffin_Technology__Inc_iMic_USB_audio_system-00.analog-stereo" FREEDV_COMPUTER_TO_SPEAKER_DEVICE="alsa_output.pci-0000_00_01.0.analog-stereo" FREEDV_MICROPHONE_TO_COMPUTER_DEVICE="alsa_input.pci-0000_00_01.0.analog-stereo" PYTHONPATH=$(pwd)/rade_src ctest -R fullduplex; done
```

(Optional) Load is added by running X number of `yes >/dev/null &` until `top`/Activity Monitor/other OS equivalent shows 75-80% CPU usage across all cores/threads before running the "With Load" tests.

### Windows

Copy `TestFreeDVFullDuplex.ps1` and `freedv-ctest-fullduplex.conf.tmpl` to the FreeDV install location (i.e. `C:\Program Files\FreeDV 2.0.0...\bin`), then open PowerShell and execute the following:

```
PS> cd 'C:\Program Files\FreeDV 2.0.0...\bin'
PS> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
PS> .\TestFreeDVFullDuplex.ps1 `
    -RadioToComputerDevice "Microphone (iMic USB audio system)" `
    -ComputerToSpeakerDevice "Speakers (Realtek High Definition Audio(SST))" `
    -MicrophoneToComputerDevice "Microphone Array (Realtek High Definition Audio(SST))" `
    -ComputerToRadioDevice "Speakers (iMic USB audio system)" `
    -NumberOfRuns 10 -ModeToTest RADE
```

(replace the various audio devices and mode to test as needed; the iMic devices above are the ones corresponding to the USB audio device with the loopback cable.)

Note that you may need to mute and unmute audio in Windows to allow it to be passed through to FreeDV prior to initially executing tests (Windows bug?)

(Optional) For load tests, see https://am2.co/2018/06/generating-artificial-cpu-load/ for a script that will generate the CPU load needed.

## Success Criteria

`ctest` and the PowerShell script above start FreeDV in "full duplex" mode, causing TX and RX to occur at the same time. Because of the audio cable linking the Mic and Speaker ports on the USB audio device, FreeDV receives the signal that was just "transmitted". While this is happening, the tests look for "Sync changed" output on FreeDV's `stderr` and count the number of times this occurs. "Sync changed" occurs when `freedv_get_sync()` / `rade_get_sync()` changes from 0 to 1 (or vice versa). A "pass" is defined as this occurring only once, when FreeDV initially gets sync. Each scenario/mode must pass ten times in order for it to count as "passing".

### No Load (FreeDV only active task)

| Platform | Commit tested | 700D | 700E | 1600 | RADE |
|---|---|---|---|---|---|
| macOS (PortAudio) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Linux (pipewire) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Windows 1 (PortAudio) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Windows 2 (PortAudio) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Windows 3 (PortAudio) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |

### Load Tests (Informational Only)

| Platform | Commit tested | 700D | 700E | 1600  | RADE |
|---|---|---|---|---|---|
| macOS (PortAudio) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Linux (pipewire) | e21a3f0 | 10/10 | 10/10 | 10/10 | 10/10 |
| Windows 1 (PortAudio) | e21a3f0  | 10/10 | 10/10 | 10/10 | 5/10 (75% load)<br>10/10 (50% load) |

### CODE REVIEW

**Comment by tmiw** [comment]
Need to figure out why `snd-aloop` isn't available in GH actions and then write the appropriate test script(s). Though it's possible this might only be a test that can be manually started (but 100% automated otherwise).

**Comment by tmiw** [comment]
Updated the test to check for and output any changes to the sync status once per second. This should probably happen more often, though. Would something like every 100ms be sufficient?

**Comment by tmiw** [comment]
So I think I have full duplex ctests working with pipewire loopback devices (and in the GH action, too). I did notice something on my setup here where FreeDV seemed to be getting audio in large batches instead of smaller chunks like I'd expect. I remember seeing this before during the PulseAudio integration but I chalked it up to something with loopback devices as testing on actual audio devices worked okay.

Anyway, the most recent commit adds RADE to the ctests (700D/E/1600 worked with the run in [89e9cff](https://github.com/drowe67/freedv-gui/pull/761/commits/89e9cff7df0418a477da232306e23f6da1bcf57b)) so we'll see how that goes.

**Comment by tmiw** [comment]
FYI, from the RADE ctest:

```
1: Firing stop
1: 501 state: search     valid: 0 0  0 Dthresh:     0.00 Dtmax12:     0.00     0.00 tmax:    0 fmax:   0.00
1: [2024-11-03 20:27:51] [disconnect] Disconnect close local:[1000,End by user] remote:[1000]
1: 20:27:51: Debug: 1 threads were not terminated by the application.
 1/10 Test  #1: fullduplex_RADE ..................   Passed   74.78 sec
```

**Comment by tmiw** [comment]
So, apparently the tests weren't actually working in the GitHub environment. I noticed this when I looked at the logs and realized that RADE was never getting sync in full duplex mode. I've been trying various things to get pipewire working properly without success thus far. The only difference I can see (other than some `rtkit` errors and Bluetooth related stuff which seem safe to ignore) is what `wpctl status` shows 30s into the test:

*Local environment*:

```
mooneer@ubuntu-vm:~/freedv-gui/build_linux$ pactl info
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 914
Tile Size: 65472
User Name: mooneer
Host Name: ubuntu-vm
Server Name: PulseAudio (on PipeWire 1.0.5)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_02_02.0.analog-stereo
Default Source: alsa_input.pci-0000_02_02.0.analog-stereo
Cookie: fe9f:37fd
```

```
2: PipeWire 'pipewire-0' [1.0.5, mooneer@ubuntu-vm, cookie:4271847421]
2:  └─ Clients:
2:         32. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2:         33. WirePlumber                         [1.0.5, mooneer@ubuntu-vm, pid:2395]
2:         34. WirePlumber [export]                [1.0.5, mooneer@ubuntu-vm, pid:2395]
2:         52. gnome-shell                         [1.0.5, mooneer@ubuntu-vm, pid:2600]
2:         53. GNOME Shell Volume Control          [1.0.5, mooneer@ubuntu-vm, pid:2600]
2:         54. GNOME Volume Control Media Keys     [1.0.5, mooneer@ubuntu-vm, pid:2766]
2:         55. xdg-desktop-portal                  [1.0.5, mooneer@ubuntu-vm, pid:3152]
2:         56. Mutter                              [1.0.5, mooneer@ubuntu-vm, pid:2600]
2:         63. paplay                              [1.0.5, mooneer@ubuntu-vm, pid:8491]
2:         66. FreeDV HF Digital Voice             [1.0.5, mooneer@ubuntu-vm, pid:8492]
2:         79. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2:         89. Terminal                            [1.0.5, mooneer@ubuntu-vm, pid:3472]
2:         96. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2:        100. wpctl                               [1.0.5, mooneer@ubuntu-vm, pid:8519]
2:        103. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2:        114. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2:        121. pipewire                            [1.0.5, mooneer@ubuntu-vm, pid:2396]
2: 
2: Audio
2:  ├─ Devices:
2:  │      48. ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) [alsa]
2:  │  
2:  ├─ Sinks:
2:  │  *   49. ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo [vol: 0.40]
2:  │      98. FreeDV_Computer_To_Radio            [vol: 1.00]
2:  │     105. FreeDV_Radio_To_Computer            [vol: 1.00]
2:  │     113. FreeDV_Microphone_To_Computer       [vol: 1.00]
2:  │     115. FreeDV_Computer_To_Speaker          [vol: 1.00]
2:  │  
2:  ├─ Sink endpoints:
2:  │  
2:  ├─ Sources:
2:  │  *   50. ES1371/ES1373 / Creative Labs CT2518 (Audio PCI 64V/128/5200 / Creative CT4810/CT5803/CT5806 [Sound Blaster PCI]) Analog Stereo [vol: 1.00]
2:  │  
2:  ├─ Source endpoints:
2:  │  
2:  └─ Streams:
2:         58. paplay                                                      
2:              60. output_FR       > FreeDV_Microphone_To_Computer:playback_FR	[active]
2:              75. output_FL       > FreeDV_Microphone_To_Computer:playback_FL	[active]
2:         59. FreeDV HF Digital Voice                                     
2:              85. output_FL       > FreeDV_Computer_To_Radio:playback_FL	[active]
2:              93. output_FR       > FreeDV_Computer_To_Radio:playback_FR	[active]
2:         64. FreeDV HF Digital Voice                                     
2:              57. output_FR       > FreeDV_Computer_To_Speaker:playback_FR	[active]
2:              94. output_FL       > FreeDV_Computer_To_Speaker:playback_FL	[active]
2:         65. FreeDV HF Digital Voice                                     
2:              86. monitor_FR     
2:              87. input_FR        < FreeDV_Radio_To_Computer:monitor_FR	[active]
2:              95. monitor_FL     
2:             111. input_FL        < FreeDV_Radio_To_Computer:monitor_FL	[active]
2:         68. FreeDV HF Digital Voice                                     
2:              69. input_FL        < FreeDV_Microphone_To_Computer:monitor_FL	[active]
2:              81. input_FR        < FreeDV_Microphone_To_Computer:monitor_FR	[active]
2:              88. monitor_FR     
2:             129. monitor_FL     
2:         80. output.loopback-2396-13                                     
2:              76. output_FR       > FreeDV_Radio_To_Computer:playback_FR	[active]
2:              91. output_FL       > FreeDV_Radio_To_Computer:playback_FL	[active]
2:         84. input.loopback-2396-13                                      
2:              70. monitor_FR     
2:              72. input_FR        < FreeDV_Computer_To_Radio:monitor_FR	[active]
2:              77. monitor_FL     
2:              78. input_FL        < FreeDV_Computer_To_Radio:monitor_FL	[active]
2: 
2: Video
2:  ├─ Devices:
2:  │  
2:  ├─ Sinks:
2:  │  
2:  ├─ Sink endpoints:
2:  │  
2:  ├─ Sources:
2:  │  
2:  ├─ Source endpoints:
2:  │  
2:  └─ Streams:
2: 
2: Settings
2:  └─ Default Configured Node Names:
```

*GitHub:*

```
Server String: /run/user/1001/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 42
Tile Size: 65472
User Name: runner
Host Name: fv-az1215-275
Server Name: PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: auto_null
Default Source: auto_null.monitor
Cookie: 6a15:0984
```

```
4: PipeWire 'pipewire-0' [0.3.48, runner@fv-az1215-275, cookie:1779763588]
4:  └─ Clients:
4:         32. pipewire                            [0.3.48, runner@fv-az1215-275, pid:22966]
4:         33. WirePlumber                         [0.3.48, runner@fv-az1215-275, pid:22967]
4:         34. WirePlumber [export]                [0.3.48, runner@fv-az1215-275, pid:22967]
4:         39. pactl                               [0.3.48, runner@fv-az1215-275, pid:23329]
4:         45. paplay                              [0.3.48, runner@fv-az1215-275, pid:23335]
4:         54. pactl                               [0.3.48, runner@fv-az1215-275, pid:23332]
4:         61. pipewire                            [0.3.48, runner@fv-az1215-275, pid:22966]
4:         64. pactl                               [0.3.48, runner@fv-az1215-275, pid:23331]
4:         65. pactl                               [0.3.48, runner@fv-az1215-275, pid:23330]
4:         79. FreeDV HF Digital Voice             [0.3.48, runner@fv-az1215-275, pid:23336]
4:        104. wpctl                               [0.3.48, runner@fv-az1215-275, pid:23394]
4: 
4: Audio
4:  ├─ Devices:
4:  │  
4:  ├─ Sinks:
4:  │      42. FreeDV_Computer_To_Radio            [vol: 1.00]
4:  │      43. FreeDV_Microphone_To_Computer       [vol: 1.00]
4:  │  *   48. FreeDV_Radio_To_Computer            [vol: 1.00]
4:  │      55. FreeDV_Computer_To_Speaker          [vol: 1.00]
4:  │  
4:  ├─ Sink endpoints:
4:  │  
4:  ├─ Sources:
4:  │  
4:  ├─ Source endpoints:
4:  │  
4:  └─ Streams:
4:         62. paplay                                                      
4:              75. output_FR       > FreeDV_Microphone_To_Computer:playback_FR
4:              77. output_FL       > FreeDV_Microphone_To_Computer:playback_FL
4:         66. input.loopback-12                                           
4:              41. input_FL        < FreeDV_Computer_To_Radio:monitor_FL
4:              63. monitor_FL     
4:              68. monitor_FR     
4:              70. input_FR        < FreeDV_Computer_To_Radio:monitor_FR
4:         71. output.loopback-12                                          
4:              60. output_FL       > FreeDV_Radio_To_Computer:playback_FL
4:              69. output_FR       > FreeDV_Radio_To_Computer:playback_FR
4:         82. FreeDV HF Digital Voice                                     
4:              81. output_FL       > FreeDV_Computer_To_Radio:playback_FL
4:             100. output_FR       > FreeDV_Computer_To_Radio:playback_FR
4:         87. FreeDV HF Digital Voice                                     
4:              83. input_FR        < FreeDV_Microphone_To_Computer:monitor_FR
4:              92. monitor_FR     
4:              96. monitor_FL     
4:             102. input_FL        < FreeDV_Microphone_To_Computer:monitor_FL
4:         90. FreeDV HF Digital Voice                                     
4:              85. input_FR        < FreeDV_Radio_To_Computer:monitor_FR
4:              89. input_FL        < FreeDV_Radio_To_Computer:monitor_FL
4:              93. monitor_FL     
4:              97. monitor_FR     
4:         91. FreeDV HF Digital Voice                                     
4:              98. output_FR       > FreeDV_Computer_To_Speaker:playback_FR
4:             101. output_FL       > FreeDV_Computer_To_Speaker:playback_FL
4: 
4: Video
4:  ├─ Devices:
4:  │  
4:  ├─ Sinks:
4:  │  
4:  ├─ Sink endpoints:
4:  │  
4:  ├─ Sources:
4:  │  
4:  ├─ Source endpoints:
4:  │  
4:  └─ Streams:
4: 
4: Settings
4:  └─ Default Configured Node Names:
```

(Note the lack of `[active]` for the GH run. Not sure if this matters.)

I also enabled some pipewire/wireplumber debug output at https://github.com/drowe67/freedv-gui/actions/runs/11673582830/job/32504604516?pr=761, but I'm not seeing anything popping out at first glance. 

pipewire/dbus/etc. are also initialized on GH as follows:

```yaml
    - name: Execute unit tests
      shell: bash
      working-directory: ${{github.workspace}}/build_linux
      run: |
          sudo systemctl enable rtkit-daemon
          sudo systemctl start rtkit-daemon
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 5
          export DISPLAY=:99.0
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          mkdir -p $XDG_RUNTIME_DIR
          chmod 700 $XDG_RUNTIME_DIR
          eval "$(dbus-launch --sh-syntax --exit-with-x11)"
          #systemctl --user --now enable wireplumber pipewire pipewire-pulse
          export PIPEWIRE_DEBUG=I
          export WIREPLUMBER_DEBUG=I
          pipewire &
          pipewire-pulse &
          wireplumber &
          sleep 5
          pactl info
          wpctl status
          metacity --sm-disable --replace &
          sleep 5
          ln -s ${{github.workspace}}/build_linux/rade_src/model19_check3 model19_check3
          . ../rade-venv/bin/activate
          PYTHONPATH=${{github.workspace}}/build_linux/rade_src:$PYTHONPATH ctest -V
```

Actually it looks like GH uses a different pipewire than my local setup, despite both theoretically being Ubuntu 24.04. I should already be doing `apt-get update` before installing pipewire but maybe I need to `apt-get upgrade` too. I'll try that now, but if @Tyrbiter or anyone else with more pipewire knowledge than I do has any ideas, I'm welcome to hear them.

**Comment by tmiw** [comment]
Huh, I think updating the GH action to Ubuntu 24.04 (turns out `ubuntu-latest` is actually 22.04) worked in the sense that audio is now getting passed to freedv-gui in the ctest. However, I'm still getting intermittent failures, so I'm going to look into beefing up reliability some more.

**Comment by tmiw** [comment]
I've been doing some tests with a Griffin iMic and a cable connecting the mic and speaker ports. That's definitely working better than the pipewire loopback devices. I think there's still a problem with those devices; for example, the "Bits" field seems to increment a lot more quickly with the legacy modes when using an external audio device. As I don't think their use is likely, I'm going to take a break from investigating that for now.

Anyway, I have some pending changes here that also let me run `test_zeros.sh` on macOS (with that same Griffin iMic audio device). i.e.

```
$ FREEDV_COMPUTER_TO_RADIO_DEVICE="iMic USB audio system" FREEDV_RADIO_TO_COMPUTER_DEVICE="iMic USB audio system" FREEDV_COMPUTER_TO_SPEAKER_DEVICE="VB-Cable" FREEDV_MICROPHONE_TO_COMPUTER_DEVICE="VB-Cable" ../test_zeros.sh txrx 700D
```

I'll see what happens when I run `ctest`.

**Comment by tmiw** [comment]
I'm currently running through the "load" tests with the Raspberry Pi but things look good at least with macOS and Linux otherwise (I gave up entirely on trying to run stuff in VMs since the process of providing USB devices to the VMs is adding too much variance). [f16c27f](https://github.com/drowe67/freedv-gui/pull/761/commits/f16c27f4d3d1e55be148f955e1d1a0be71725516) actually did help with that a bit for Linux but it's a big enough change (combined with not seeming to make a difference on actual hardware) that I'm not too comfortable with it.

Anyway, once done with the load testing I'll go ahead and work on a PowerShell script that Windows users can run to validate behavior. I plan on running this for RADE at least for the "unloaded" case (I'm still not sure how to generate load on Windows) to hopefully show equivalence to the other PortAudio platforms (namely macOS).

**Comment by tmiw** [comment]
Last night I noticed that I was only getting 8-9/10 passed (depending on the mode) during the load test on Linux. Even in the cases when it did pass, the BER seemed much higher than it should have been. Running FreeDV manually with the same hardware, of course, showed that everything was good. 

Anyway, I just checked in another change that I'm hoping will help. BER at least seems a lot better so far. Will update once I have results.

**Comment by tmiw** [comment]
Cool, that latest commit fixed the load issue on the Raspberry Pi 5. Now to think of something for Windows and hopefully we'll be able to close this out.

**Comment by drowe67** [comment]
Hi @tmiw.  Thanks for putting so much work into this - I went through the same process when 700D was released so I feel your pain.  It's a messy issue to test and doesn't lend itself well to full automated/GitHub action approach.   

However - it is *really important* we have a rock solid sample playback/record system to support the FreeDV project as a whole.  No point spending years on breakthrough modes like RADE to have it messed up by buffer slips.

A few general comments:

1. Any way to get others to reproduce?  E.g. PLT team/other volunteers
2. Silence should not be the metric, it's possible to have a buffer slip without silence, but it looks like (despite the PR title) you've moved to sync as the metric :+1: 
3. We need more representative machines that a Windows tablet
4. I don't feel results on a VM are relevant, except perhaps as a way to functionally test the code.  Same with the Pi - lets not go there.
5. Focus on Windows.
6. While the additional load step could be used to induce problems/stress test, not sure its part of typical use case.  I'd be happy to call a pass Windows+RADE with no load (the typical RADE load is already pretty heavy).
7. full duplex is an extreme case, but if that passes I guess we are good, and I get that it simplifies testing
8. Modes other than RADE are becoming increasingly irrelevant, maybe just need 1 or 2 in the results.
9. Running in Github actions is a "nice to have" I guess, to avoid any bugs creeping in.  But GH actions, VMs, or tests without hardware are not strong.  Really need hardware in the loops, multiple hardware examples (PC+sound card).

So what I'd suggest to close this out:
1. Focus on Windows+RADE+no load case.
2. Somehow get the test into a form where say 2 other people can run it on Windows machines with their sound card hardware.  (Or even you could do that if you can get your hands on some other hardware examples).
3. Some sort of long term/automated test that we can leave running would be nice - but it's a similar problem to the stm32 tests, we really need hardware in the loop permanently.  I'm a bit stuck on that one :thinking: 

If we can't get a solid pass with RADE+Windows we should have another rethink, either about the pass metrics or look at the sound I/O design.

BTW I'm not sure I have notification set up write for freedv-gui :thinking: .  I should be pinged when I get a @drowe67

**Comment by tmiw** [comment]
I updated the title and description based on the comments. I kept the test results recorded so far for our reference.

> 1. Any way to get others to reproduce?  E.g. PLT team/other volunteers

I'll ask around once I update the PowerShell script I've been using. Ideally someone should be able to copy it to the correct location and just run it, no editing of the script required.

> 3. We need more representative machines than a Windows tablet

It should be using similar hardware as normal Windows PCs (as well as similar OS), but yeah, it's probably not a common use scenario.

> 6. While the additional load step could be used to induce problems/stress test, not sure its part of typical use case.  I'd be happy to call a pass Windows+RADE with no load (the typical RADE load is already pretty heavy).

👍 

> BTW I'm not sure I have notification set up write for freedv-gui 🤔 . I should be pinged when I get a @drowe67

Testing: @drowe67

**Comment by tmiw** [comment]
> Hmm, no I'm not getting notifications ... Ill push a few more Github buttons.

Hopefully you're able to figure out why, @drowe67.

BTW I asked Walter to try to duplicate the above results on his end with an updated version of the PowerShell script (which I'll be checking in hopefully tonight or tomorrow). I may have a second machine at home I can try it with, too--if I can find it (long story).

**Comment by tmiw** [comment]
@drowe67, OK, so I got RADE tests working on Windows in the GH action. (I know, not strictly necessary, but will be good once we start adding more test coverage.) Still waiting on Walter K5WH to give me results from his machine to update above. I'll ping him when I have a chance.

**Comment by drowe67** [comment]
> @drowe67, OK, so I got RADE tests working on Windows in the GH action. (I know, not strictly necessary, but will be good once we start adding more test coverage.) Still waiting on Walter K5WH to give me results from his machine to update above. I'll ping him when I have a chance.

That's a neat trick - is there any correlation between the tests failing in the GH actions environment and tests failing with real HW?  Just trying to make sure the GH actions tests can trap at least a subset of bugs in this area.

Yep results from a few typical machines/sound cards would be very useful.

**Comment by drowe67** [comment]
@tmiw - did the tests in this PR lead you to any improvements in the sound code, or was it all OK and passed the tests without modification?

**Comment by tmiw** [comment]
> That's a neat trick - is there any correlation between the tests failing in the GH actions environment and tests failing with real HW? Just trying to make sure the GH actions tests can trap at least a subset of bugs in this area.

I've found some correlation on the Linux/PulseAudio side, at least. I also found some error handling bugs that will be handled separately: https://github.com/drowe67/freedv-gui/issues/772

> @tmiw - did the tests in this PR lead you to any improvements in the sound code, or was it all OK and passed the tests without modification?

I ended up fixing some issues with the PulseAudio side. Otherwise I think things mostly matched up.

**Comment by tmiw** [comment]
@drowe67, just added the results I got from Walter to the top of the PR. Looks like we might be good?

**Comment by drowe67** [comment]
> @drowe67, just added the results I got from Walter to the top of the PR. Looks like we might be good?

Well done @tmiw (and thanks Walter).  I appreciate all your hard work on this one :+1:

**Comment by tmiw** [comment]
> > @drowe67, just added the results I got from Walter to the top of the PR. Looks like we might be good?
> 
> Well done @tmiw (and thanks Walter). I appreciate all your hard work on this one 👍

No worries. OK to merge now?

**Pull request merged**
