### PR TITLE
Tweaks to make FreeDV work better with pipewire

### PR DESCRIPTION
**Pull request by tmiw**
Per #238 and other previous discussion, this PR integrates changes required to make FreeDV work a bit better with pipewire.

### CODE REVIEW

**Comment by Tyrbiter** [comment]
Is there a simple way of outputting the timestamp in timedate format, or whatever it is journalctl outputs?

**Comment by tmiw** [comment]
> Is there a simple way of outputting the timestamp in timedate format, or whatever it is journalctl outputs?

Try now? It should output timestamps per the format described at https://en.cppreference.com/w/c/chrono/ctime.

**Comment by Tyrbiter** [comment]
Thanks @tmiw, for some reason there is a LF before the ] after the first %s string substitution, I assume it's something to do with the ctime output. Not a major headache, just a readability thing.

**Comment by tmiw** [comment]
> Note sure if fprintf can swallow that \n somehow.

I switched it to using strftime instead based on the comments [here](https://stackoverflow.com/questions/9101590/fprintf-and-ctime-without-passing-n-from-ctime).

> One other minor thing, opening the Filter menu gives this in the console window:
> 
> (freedv:316054): Gtk-WARNING **: 17:33:41.313: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
> 
> Seems to be the default button on the top right I think.

Hmm, just tried to open the Filter dialog in my Ubuntu development VM (21.10) and didn't see that warning. Do you see any rendering issues with that window?

**Comment by Tyrbiter** [comment]
> Hmm, just tried to open the Filter dialog in my Ubuntu development VM (21.10) and didn't see that warning. Do you see any rendering issues with that window?

It appears multiple times when I move the cursor over the Filter window and off it again, I don't know if there is a repaint happening each time, it doesn't seem to be but that could be down to good buffer handling.

**Comment by Tyrbiter** [comment]
Get this when attempting to build this latest:
[ 61%] Built target fdv_audio_pipeline
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/audio/PulseAudioDevice.cpp: In static member function 'static void PulseAudioDevice::StreamMovedCallback_(pa_stream*, void*)':
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/audio/PulseAudioDevice.cpp:325:16: error: declaration of 'tm* p' shadows a parameter
  325 |     struct tm *p = localtime(&result);
      |                ^
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/src/audio/PulseAudioDevice.cpp:318:56: note: 'pa_stream* p' previously declared here
  318 | void PulseAudioDevice::StreamMovedCallback_(pa_stream *p, void *userdata)
      |                                             ~~~~~~~~~~~^
gmake[2]: *** [src/audio/CMakeFiles/fdv_audio.dir/build.make:135: src/audio/CMakeFiles/fdv_audio.dir/PulseAudioDevice.cpp.o] Error 1
gmake[2]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:227: src/audio/CMakeFiles/fdv_audio.dir/all] Error 2
gmake[1]: Leaving directory '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.0/redhat-linux-build'
gmake: *** [Makefile:159: all] Error 2

**Comment by Tyrbiter** [comment]
Yes, all working fine.

**Comment by tmiw** [comment]
I'm going to merge this in so we can get a 1.8.0 out. If additional changes are needed due to pipewire, we can revisit in a new PR.

**Pull request merged**
