### PR TITLE
Add support for modifying the drop down frequency list.

### PR DESCRIPTION
**Pull request by tmiw**
Per feedback in #432, this PR adds the ability for users to modify the frequency list in the lower right hand corner of the main window (via Tools->Options->Rig Control). The new UI looks as follows:

Screenshot 2023-07-04 at 8 25 11 PM

Note: PR #457 must merge before this can as the code here depends on that PR.

### CODE REVIEW

**Comment by tmiw** [comment]
Test build with this PR and #457: https://github.com/drowe67/freedv-gui/releases/tag/v1.8.12-20230705

@barjac, @Tyrbiter

**Comment by Tyrbiter** [comment]
I have this built and installed now.

About the frequency editing, I suggest expanding the entered number 4 decimal places if it's not entered to that precision. Otherwise it seems to work,  I have added, removed and reordered some extra frequencies.

Is it possible to remove a frequency in the original list?

**Comment by tmiw** [comment]
> Is it possible to remove a frequency in the original list? I have not tried that.

Yep 👍

**Comment by Tyrbiter** [comment]
> > Is it possible to remove a frequency in the original list? I have not tried that.
> 
> Yep 👍

OK, all seems to be working well. I see that the .freedv settings file is updating and saving as it should too.

**Comment by tmiw** [comment]
> About the frequency editing, I suggest expanding the entered number to 4 decimal places if it's not entered to that precision.

Done. 👍

**Comment by Tyrbiter** [comment]
I have also merged in the PRs #461 and #462, everything is working very nicely together.

**Pull request merged**
