### PR TITLE
Client disconnects should delete from the internal data store no matter what.

### PR DESCRIPTION
**Pull request by tmiw**
Possible followup fix for #464. Basically, the current code only deletes users from the internal data store on disconnect if they're already displayed on the screen. Good when everyone was always displayed, but now that this can't be assumed anymore, causes problems with duplicate entries (especially when users end up disconnecting and reconnecting).

### CODE REVIEW

**Comment by barjac** [comment]
Yes!
Today I left the RPi4b running this branch all day along with my main system running master.
The main system has lots of multiple entries, the RPi has none so unless there any unexpected side effects this has fixed it. :)

**Comment by barjac** [comment]
On another slightly related subject, it seems that the 'receiving' colour highlight seems to turn off randomly (or maybe 10s after the last update?) irrespective of whether there is a loss of decode or not.
I have heard users commenting about the colour continually turning on and off during overs, despite good conditions and solid signals.
This is causing some confusion.
I don't know how this works, but if it is a simple timeout then maybe it could be longer?

**Comment by tmiw** [comment]
> On another slightly related subject, it seems that the 'receiving' colour highlight seems to turn off randomly (or maybe 10s after the last update?) irrespective of whether there is a loss of decode or not. I have heard users commenting about the colour continually turning on and off during overs, despite good conditions and solid signals. This is causing some confusion. I don't know how this works, but if it is a simple timeout then maybe it could be longer?

Yeah, it's a 10 second timeout, similar to the web version. Suggestions on how long it should be?

**Comment by barjac** [comment]
If it was double the expected update period then it would be unlikely to drop between updates I guess.
However the updates appear to be quite random and sometimes only a few seconds.
Is there an explanation like a logic diagram of how this works without trying to read the sources? ;)

**Comment by tmiw** [comment]
I'll go ahead and spin up another PR real quick after merging this one.

**Comment by tmiw** [comment]
https://github.com/drowe67/freedv-gui/pull/558

**Pull request merged**
