### PR TITLE
Add the ability to request that another FreeDV Reporter user QSY

### LINKED ISSUE #416: Add "request QSY" feature to FreeDV Reporter
From Rick WA6III on the digitalvoice list:

> I have a suggestion for an enhancement.   Currently we have no way to contact someone on the active list to change frequencies, unless they happen to be looking at the "Chat" tab.
>
> Since most of the computers that are running FreeDV are also connected to the internet, how about a short messaging system that will allow one user to send a "connect" request to another even though that person is on an different band.?
>
> For example, I am currently on 40M all ready to go and would like another station in the Pacific NW who is currently receiving on 14236.  Right now, 14236 is not very usable in the PNW because people are talking on SSB.
>
> I am in Washington State and I see another station in Oregon that I know is within propagation distance,   I would send him an email , but like many people, he has no posted email address in the callsign databases.
>
> If the software had some sort of P2P (obviously internet based)  messaging capability, it would be easy to get someone to switch bands frequencies etc.
>
> I do not know what this could look like and it doesn't even have to be "free text".  It could be any sort of notification alerting the other operator that someone wants him to switch freq or band etc...

(Opening an issue so we don't lose track of the discussion.)

### PR DESCRIPTION
**Pull request by tmiw**
Resolves #416 by doing the following:

* Creates a new dialog inside the FreeDV application that mimics the Active Stations tab in [FreeDV Reporter](https://qso.freedv.org/).
* Adds logic to update that dialog live, much like the Web interface.
* Provides the ability to request that another FreeDV Reporter user QSY to the user's frequency.

This PR is still a WIP. Remaining items to implement:

* Add custom messages to send along with the QSY request.
* Automatically change radio's frequency if the user accepts the QSY request.
* Others as requested?

### CODE REVIEW

**Comment by Tyrbiter** [comment]
I am seeing the same build problem with the Fedora spec file -> rpms method, looks like it is tied up with the download of the sio_client code somehow, during the build process this is where the sio_client.h ends up

/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/redhat-linux-build/sioclient_src/src

so I suspect that during the build the compiler can't find that path, although it works for 1.8.10.1 and 1.8.11:

Already on 'master'
Your branch is up to date with 'origin/master'.
Submodule 'lib/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'lib/asio'
Submodule 'lib/catch' (https://github.com/philsquared/Catch.git) registered for path 'lib/catch'
Submodule 'lib/rapidjson' (https://github.com/miloyip/rapidjson.git) registered for path 'lib/rapidjson'
Submodule 'lib/websocketpp' (https://github.com/zaphoyd/websocketpp.git) registered for path 'lib/websocketpp'
Cloning into '/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/redhat-linux-build/sioclient_src/lib/asio'...
In file included from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/src/pipeline/../freedv_reporter.h:30,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/src/pipeline/../main.h:87,
                 from /home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/src/pipeline/TxRxThread.cpp:91:
/home/bdm/rpmbuild/BUILD/freedv-gui-1.8.12/src/pipeline/../reporting/FreeDVReporter.h:33:10: fatal error: sio_client.h: No such file or directory
   33 | #include "sio_client.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/pipeline/CMakeFiles/fdv_audio_pipeline.dir/build.make:317: src/pipeline/CMakeFiles/fdv_audio_pipeline.dir/TxRxThread.cpp.o] Error 1

If I use build_linux.sh I get a freedv binary so I can test with this, I don't know if there will be many people to test this with yet.

**Comment by tmiw** [comment]
There's a crash issue with this PR due to how the list box is being handled. I'll update tonight.

**Comment by Tyrbiter** [comment]
Still seeing this build error, I think it is because there is an include statement before the sio code download so there is no sio_client.h file anywhere in the build directory tree.

Not quite sure how to sort this out, it's probably down to the way the Fedora build is done.

**Comment by Tyrbiter** [comment]
I managed to hack this by temporarily putting sio_*.h into the src/reporting directory before creating a tarball.

The first thing I notice is that the new window is sufficiently narrow that the headings are truncated:

Screenshot from 2023-06-16 13-56-48

I will see if I can get anyone to respond to requests.

**Comment by tmiw** [comment]
> I managed to hack this by temporarily putting sio_*.h into the src/reporting directory before creating a tarball.

👍 

I'll play around some more. It's weird that it works fine with `build_linux.sh` but not with the Fedora build process.

> The first thing I notice is that the new window is sufficiently narrow that the headings are truncated:

The latest commit in this PR should resolve this.

> I will see if I can get anyone to respond to requests.

Any luck so far?

**Comment by tmiw** [comment]
So I think [4fd0af4](https://github.com/drowe67/freedv-gui/pull/434/commits/4fd0af40b58993620550a8972c0e3e7f392da35b) will work around the issue you're having with Fedora. Let me know if that doesn't and I can try some CMake stuff as an alternative/in addition.

**Comment by Tyrbiter** [comment]
> So I think [4fd0af4](https://github.com/drowe67/freedv-gui/pull/434/commits/4fd0af40b58993620550a8972c0e3e7f392da35b) will work around the issue you're having with Fedora. Let me know if that doesn't and I can try some CMake stuff as an alternative/in addition.

OK, I deleted the sio_*.h files I had put in /src/reporting and applied this fix, it built just fine so the fix works for me.

**Comment by Tyrbiter** [comment]
> > The first thing I notice is that the new window is sufficiently narrow that the headings are truncated:
> 
> The latest commit in this PR should resolve this.

The headings are now fine, however the window width means there is a scrollbar, I would prefer the window to be either the full width or be resizeable.

> 
> > I will see if I can get anyone to respond to requests.
> 
> Any luck so far?

I will see what I can do, maybe I should test the feature outside an actual QSO ;-) Real life has also been in the way this week, so I will report back once I've had more opportunity in front of the radio.

**Comment by Tyrbiter** [comment]
> I'll play around some more. It's weird that it works fine with `build_linux.sh` but not with the Fedora build process.

Just realised, this works because the build_linux.sh script leaves the build_linux directory structure in place in the local git tree whereas the Fedora build process completely removes the ~/rpmbuild/BUILD/<package_name> directory after every successful build.

That means there were sio_*.h files there on each build, I usually copy and rename the git directory and then use git checkout <branch> to get the PR patches so the .h files were them from a previous build with sio code in it.

**Comment by tmiw** [comment]
> The headings are now fine, however the window width means there is a horizontal scrollbar, I would prefer the window to be either full width or be resizeable.

The window is now resizable. 👍 

> Just realised, this works because the build_linux.sh script leaves the build_linux directory structure in place in the local git tree whereas the Fedora build process completely removes the ~/rpmbuild/BUILD/<package_name> directory after every successful build.
> 
> That means there were sio_*.h files there on each build, I usually copy and rename the git directory and then use git checkout to get the PR patches so the .h files were there from a previous build with sio code in it.

Interestingly, I never ran into this despite deleting build_* before doing official Windows/macOS builds. Regardless, it's working, so we'll leave it at that.

**Comment by Tyrbiter** [comment]
> > The headings are now fine, however the window width means there is a horizontal scrollbar, I would prefer the window to be either full width or be resizeable.
> 
> The window is now resizable. +1

Thanks.

> 
> > Just realised, this works because the build_linux.sh script leaves the build_linux directory structure in place in the local git tree whereas the Fedora build process completely removes the ~/rpmbuild/BUILD/<package_name> directory after every successful build.
> > That means there were sio_*.h files there on each build, I usually copy and rename the git directory and then use git checkout to get the PR patches so the .h files were there from a previous build with sio code in it.
> 
> Interestingly, I never ran into this despite deleting build_* before doing official Windows/macOS builds. Regardless, it's working, so we'll leave it at that.
> 

Yes, don't poke a sleeping dragon.

> BTW I received your QSY request :)

I didn't quite know what happened when I clicked the button, so I clicked it to find out :) Good to know it works, I now know that it doesn't ask for the frequency, it uses the current frequency the requester is using.

**Comment by Tyrbiter** [comment]
Small thing, if the internal FreeDV Reporter window is opened before the modem is running then the column headings shown are truncated. Might be nice to tidy this up.

**Comment by tmiw** [comment]
> Small thing, if the internal FreeDV Reporter window is opened before the modem is running then the column headings shown are truncated. Might be nice to tidy this up, it only happens if opened before the first modem start has happened.

Done. 

Anyway, to @barjac and @Tyrbiter, the only thing that's missing is including an optional custom message in QSY requests. Is there value in implementing that or is this feature good for now? If the latter, I think we can merge.

**Comment by Tyrbiter** [comment]
I'm not sure about a custom message, the web page chat provides this and it's easy to use a translation add-on in a browser too.

I would say merge and see what comments come in once more people are using the feature.

**Comment by barjac** [comment]
Looks good to me.

Is there any plan to add column sorting and row colouring to the internal reporter as in the web version?

**Comment by tmiw** [comment]
> Is there any plan to add column sorting and row colouring to the internal reporter as in the web version?

I tried to add row coloring but found that it wouldn't reset itself after going back into receive, so no for now.

As for sorting, I think it's theoretically possible but it may be a significant effort based on the API wxWidgets actually provides. I'll leave it for now.

**Comment by barjac** [comment]
An alternative may be to highlight all instances of your own call in the reporter to easily see who is hearing you?
Might that be any easier to implement?

**Comment by tmiw** [comment]
I was experimenting a bit and I think I was able to work around the issue I was having with the background color not resetting. See https://github.com/drowe67/freedv-gui/pull/453.

**Comment by Tyrbiter** [comment]
I notice with PR #453 that the column widths don't update dynamically, it's a minor thing and may be a wxWidgets limitation.

Hard to catch an example, but I did see 'Transmitting' truncated in the Status column and then resizing that column meant that the Last Update column was narrowed as the overall width of the window seemed to be fixed. Yes, I know I'm being picky :) but thought it might be easily fixable...

**Comment by tmiw** [comment]
> I notice with PR #453 that the column widths don't update dynamically, it's a minor thing and may be a wxWidgets limitation.
> 
> Hard to catch an example, but I did see 'Transmitting' truncated in the Status column and then resizing that column meant that the Last Update column was narrowed as the overall width of the window seemed to be fixed. Yes, I know I'm being picky :) but thought it might be easily fixable...

I did originally have code in this PR that would auto-resize all columns every time there was an update from the server, but unfortunately this caused a *lot* of flickering. Auto-sizing now only happens when there's a new connection to the server and that seems to work reasonably well.

**Comment by Tyrbiter** [comment]
Yes, I can see it would be difficult with such a dynamic station/status listing. I'll stop worrying about it.

**Pull request merged**
