### PR TITLE
Remove "force sync" option from Tools->Options

### PR DESCRIPTION
**Pull request by tmiw**
Per comments in #317, it's desired to remove the force sync option from Tools->Options as it's no longer needed.

### CODE REVIEW

**Comment by tmiw** [comment]
@drowe67, what do you think about the ReSync button on the main window? Still a use for it despite removing the 700D force sync option?

**Comment by drowe67** [comment]
> @drowe67, what do you think about the ReSync button on the main window? Still a use for it despite removing the 700D force sync option?

Good question :thinking: It probably isn't needed, but it's sometimes fun to press and see what happens.  Might be a good question for end users.  I guess there is an argument for simplifying the GUI as much as possible - as people do get over loaded by options.

**Comment by Tyrbiter** [comment]
I did think that my discussion about 2020 modes and strange lack of decoding on successive transmissions might make this resync button useful, I don't recall using it on any other occasion.

**Comment by tmiw** [comment]
> I did think that my discussion about 2020 modes and strange lack of decoding on successive transmissions might make this resync button useful, I don't recall using it on any other occasion.
> 
> I'd say leave it for now.

On that note, I did notice that `all_2020B_mpp.wav` was being detected as 2020C the other day and thus decoded incorrectly. This button could allow it to force resync to another working mode, so yeah, we'll keep it for now.

**Pull request merged**
