### PR TITLE
Add 5368.5 KHz to default calling frequency list.

### PR DESCRIPTION
**Pull request by tmiw**
Per request from @barjac on IRC, this PR adds 5368.5 KHz to the default calling frequency list.

TODO:

- [x] Update website to reflect new location of UK net.

### CODE REVIEW

**Comment by barjac** [comment]
Thanks but not 5368 but 5368.5 :)

**Comment by tmiw** [comment]
> Thanks but not 5368.0 it is 5368.5 as per "tmiw: Please add 5368.5 kHz....." :)

Oops, updated.

**Comment by tmiw** [comment]
Quick question: do the frequencies in either of the UK lines below need to be replaced with 5368.5, or is it an additional frequency alongside it?

Screenshot 2023-12-24 at 10 29 41 AM

**Comment by barjac** [comment]
The Sunday RSGB news is generally on 3640 but 3643 is the usual alternative if QRM/occupied.

The daily net is on 5368.5 kHz at present but depending on band conditions (time of year) may move to 80m as listed above. 5366.5 is unlikely to be used again in the UK for FreeDV as it clashes with a regular group using Olivia.

So yes, 5368.5 kHz needs a new entry for UK net and the RSGB News needs to list 3640 kHz as primary freq.

**Comment by tmiw** [comment]
> The Sunday RSGB news from GB2RS (by Matt G6WPJ) is generally on 3640 but 3643 is the usual alternative if QRM/occupied.
> 
> The daily FreeDV UK net is on 5368.5 kHz at present but depending on band conditions (time of year) may move to 80m as listed above. 5366.5 is unlikely to be used again in the UK for FreeDV as it clashes with a regular group using Olivia.
> 
> So yes, 5368.5 kHz needs a new entry for UK net and the RSGB News needs to list 3640 kHz as primary freq.

OK, updated as follows:

Screenshot 2023-12-25 at 12 23 22 AM

**Pull request merged**
