### PR TITLE
Fix single device sound card configuration

### PR DESCRIPTION
**Pull request by tmiw**
@drowe67, I installed pavucontrol in my Ubuntu VM tonight and ended up accidentally running into an issue with how single sound card configs are saved in 1.5.2. This PR is to fix that at least. 

(BTW, PulseAudio in a single sound card configuration seems to work in brief testing, but I also wasn't trying to run other apps that use it along with FreeDV.)

EDIT: typo of "pavucontrol".

### CODE REVIEW

**Comment by drowe67** [comment]
> (BTW, PulseAudio in a single sound card configuration seems to work in brief testing, but I also wasn't trying to run other apps that use it along with FreeDV.)

Yes I've had some success using the Pulse playback device, when some other device has grabbed the default device.

**Comment by tmiw** [comment]
@drowe67, yeah, I'd possibly try to flesh out more info so that we have a defined scope of work for #16 (if there is in fact anything needed).

Anyway, returning to this PR, I emailed the build I sent to the digitalvoice tonight out to Walter and a few others for testing. I think someone else on Windows ran into this issue too but need to confirm for sure.

**Comment by drowe67** [comment]
@tmiw is this one ready to merge?

**Comment by tmiw** [comment]
@drowe67, yep, I haven't heard of any issues so we're good here.

**Pull request merged**
