### PR TITLE
Horus Binary Updates

### PR DESCRIPTION
**Pull request by darksidelemm**
Updates the call to horus_rx to match the changes made in https://github.com/drowe67/codec2/pull/96

Also updates the user manual to refer out to the Horus Binary setup guide.

### CODE REVIEW

**Comment by darksidelemm** [comment]
Note that I fully expected this CI build to fail, as it depends on changes to codec2. Not sure how you deal with that in CI!

**Comment by drowe67** [comment]
> Note that I fully expected this CI build to fail, as it depends on changes to codec2. Not sure how you deal with that in CI!

You can change the branch ```build.sh``` uses https://github.com/drowe67/freedv-gui/blob/master/build_linux.sh#L11

However need to set that back to master before a merge.

**Comment by drowe67** [comment]
@darksidelemm silly question but have you tested the changes with freedv-gui by running freedv-gui with Horus signals?  I don't think these changes can break anything else in freedv-gui (e.g. the FreeDV modes).

Once we get your codec 2 changes merges this PR should start building properly, and we can merge.

**Comment by darksidelemm** [comment]
Yes, I've done a complete build of freedv_gui against my modified codec2_branch and run it against off-air signals - no problems found!

**Comment by darksidelemm** [comment]
There we go, CI passes!

**Pull request merged**
