### PR TITLE
Allow display and entry of frequencies in KHz

### LINKED ISSUE #583: Add option for frequency entry in KHz instead of MHz
A request was submitted via the digitalvoice mailing list to provide an option to enter frequencies in KHz instead of MHz (i.e. "14236" instead of "14.236"). This issue was created so that this request isn't lost and can be evaluated further.

### PR DESCRIPTION
**Pull request by tmiw**
Resolves #583 by adding a new configuration option to allow display and entry of frequencies in KHz.

### CODE REVIEW

**Comment by Tyrbiter** [comment]
This seems to work OK, but should the entry list in the Options dialog also change to kHz when this option is selected?

**Comment by tmiw** [comment]
> This seems to work OK, but should the entry list in the Options dialog also change to kHz when this option is selected?

It should already be doing that (I tested last night to be sure), albeit you need to push Apply or OK first.

**Comment by Tyrbiter** [comment]
OK, yes, seems to work. If a value already exists in the entry box, say 1.997MHz,  then this turns into 1.997kHz after changing the setting and applying it. Might be a bit confusing.

**Comment by tmiw** [comment]
> OK, yes, seems to work. If a value already exists in the entry box, say 1.997MHz, then this turns into 1.997kHz after changing the setting and applying it. Might be a bit confusing.

Should be fixed now :)

**Comment by Tyrbiter** [comment]
> > OK, yes, seems to work. If a value already exists in the entry box, say 1.997MHz, then this turns into 1.997kHz after changing the setting and applying it. Might be a bit confusing.
> 
> Should be fixed now :)

And indeed it is, thanks.

**Pull request merged**
