### PR TITLE
Fix missed wxWidgets 3.1 assertions.

### PR DESCRIPTION
**Pull request by tmiw**
Just tried the play/record options in the menu and it looks like I missed a couple of assertions. Oops!

\+ @drowe67, @ra1nb0w

### CODE REVIEW

**Comment by ra1nb0w** [comment]
works fine.

**Comment by drowe67** [comment]
Nice catch @tmiw - shall we leave this PR open for a bit in case other issues appear I would you prefer I merge now?

**Comment by tmiw** [comment]
I think merging now is okay; I clicked though all of the menu options again to make sure and I haven't seen any other assertions. Additionally, I grepped the code for potentially problematic controls (e.g. anything alignment related along with wxALL and/or wxEXPAND) and didn't see anything not already exercised.

**Comment by drowe67** [comment]
Thanks @tmiw for testing so thoroughly.  I figure by merging we'll soon see if anything else turns up :slightly_smiling_face:

**Pull request merged**
