### PR TITLE
Left justify data and labels, remove '--' and align data start with label start for easier readability and cleaner looks

### PR DESCRIPTION
**Pull request by barjac**
This PR attempts to improve the readability and looks of the internal reporter by left aligning all the data in each column rather than centring it within the current column widths which looks ragged. 

It makes sure that the start of each data item is below the start of the column label.

It removes the '--' items which indicate that there is no data. However we can see that there is no data if there is nothing there.
I can maybe understand using this in a purely testing environment but not for production as it is serving no purpose.

I will add a screen shot later.

### CODE REVIEW

**Comment by barjac** [comment]
Screenshot_20240105_095612

**Comment by barjac** [comment]
> Thanks for creating this PR! Were you able to do any experimentation to see if it were possible to keep the column titles center aligned while left aligning everything else? I remember trying before and being unable to.

I read some wx docs and could see nothing, but I really don't think that would be better.
Having the label accurately aligned with the data does not look bad at all. If the data includes narrow items as in the Msg column alongside the odd wide one, then a centred label could be very misaligned with the narrow item.
I used it in our daily 60m net today and took a screen shot. (Will add from a other machine shortly)

**Comment by Tyrbiter** [comment]
I'm not against this, however I think it may not be ideal for the distance and SNR columns, I think that they look better if right-justified.

**Comment by barjac** [comment]
> I'm not against this, however I think it may not be ideal for the distance and SNR columns, I think that they look better if right-justified. Perhaps for distance the own station value should be 0 or blank instead of 0.0 as well.

Yes I agree, seems odd that 0 is displayed as 0.0.

**Comment by tmiw** [comment]
I was doing a bit more reading on UX standards for tables and they seem to have the following in common:

* Text: left aligned
* Numbers: right aligned
* Column header alignment should match data

Example guidance: https://medium.com/mission-log/design-better-data-tables-430a30a00d8c

With that in mind, I pushed some changes to right-align "km/mi", "kHz/MHz", and "SNR" columns. It actually significantly improved it for me to the point where I think it might be counterproductive to center align the column headings (assuming that's actually possible without significant changes to wxWidgets itself). Hopefully that's okay for you guys too, but if not, we can revert and just have everything left aligned.

**Comment by barjac** [comment]
I did a similar thing today before reading your last above. I also removed the check for distance < 10.0 which solved the 0.0 issue for me. I'm getting a bit lost in github - I don't see your changes :(

Screenshot_20240106_124107

**Comment by Tyrbiter** [comment]
I've just made the changes as suggested, with dates centre-justified but then other text left-justified and numbers right-justified.

Also removed the <10.0 distances units check and that's nicer IMHO.

Not completely sure about the centred dates, I think that it's probably quite a weak change and is probably font-dependent.

**Comment by tmiw** [comment]
Yeah, considering the width of the text in the date columns, I don't think there's much difference other than for the headers. I'd say to back out that particular change to be more consistent with the other text-based columns.

**Comment by barjac** [comment]
OK the dates are back to left justified and I am very happy with it now. Note I also changed mi to Miles which looks much better and in most cases causes no width overhead.

Screenshot_20240106_201857

**Comment by tmiw** [comment]
> Note I also changed mi to Miles which looks much better and in most cases causes no width overhead.

Seems like we'd want to keep it consistent with both units, right? As in, either abbreviate both or use the full name for both.

Though I'm also fine just using "Miles" if that is indeed better.

**Comment by barjac** [comment]
> > Note I also changed mi to Miles which looks much better and in most cases causes no width overhead.
> 
> Seems like we'd want to keep it consistent with both units, right? As in, either abbreviate both or use the full name for both.

No not really! 'Kilometers' is too long, 'Miles' is not and if you only use one of them then you will not care! ;)
> 
> Though I'm also fine just using "Miles" if that is indeed better.

Looks much better to me, 'mi' looks like an SI unit that I never heard of and it's not a common abbreviation for mile. :)

**Comment by barjac** [comment]
I was trying to figure out what was causing the 'Last update' to be pushed off my screen. It appears to be mainly down to someone using an eight character locator. Can this field be limited to 6 characters? ...and lower case conversion for the last two?
Also SNR column seems over wide as it only ever needs 4 characters.
Miles/km is also wider than needed as it only needs 5 digits, unless it's catering for interplanetary contacts :)
By manually adjusting these the whole table fits again.

Screenshot_20240106_224900

**Comment by tmiw** [comment]
I'll go ahead and merge, then work on the stuff mentioned in the very last comment above.

**Pull request merged**
