### PR TITLE
Improvements for visually impaired users

### PR DESCRIPTION
**Pull request by tmiw**
Partial fix for #120 by adding tool tips for the Tools menu as well as keyboard shortcuts. Also potentially fixes for other issues in the application depending on what's discovered.

### CODE REVIEW

**Comment by tmiw** [comment]
See #119 for info about the change in 89807c0. Definitely didn't mean to also include it in this PR.

**Comment by tmiw** [comment]
@drowe67, would it be possible to get some input from other visually impaired users on the current FreeDV codebase? While I did use NVDA to go through most of the UI elements, I'm sure I missed a bunch of other stuff too.

**Comment by drowe67** [comment]
Hi @timw, thanks for working in this one.  A few years we did indeed have a blind ham provide some feedback, he was a vk8 I believe, I will see if I can find his contact details (I've had a hard disk crash since then and lost many email addresses).

However happy to have feedback from anyone in the visually impaired Ham community.

**Comment by drowe67** [comment]
@tmiw I can't seem to find the email of the visually impaired VK8 who helped us out last time.  Shall we keep this one open for a while until we get some feedback form some visually impaired end users?

**Comment by tmiw** [comment]
> @tmiw I can't seem to find the email of the visually impaired VK8 who helped us out last time. Shall we keep this one open for a while until we get some feedback form some visually impaired end users?

Seems reasonable to me.

**Comment by tmiw** [comment]
@drowe67, I haven't heard any other feedback about this (other than Neil re: Hamlib/FLrig), so I think this is okay to merge.

**Comment by drowe67** [comment]
> @drowe67, I haven't heard any other feedback about this (other than Neil re: Hamlib/FLrig), so I think this is okay to merge.

@tmiw you've put so much work into this! Plus it's spun off other PRs like the windows build system improvements. So I really feel:

1. We need to get feedback from visually impaired users before merging.  I'll ping them again.
1. Given all the changes it might be useful for regular users to try it too.  I'll do that this week.

**Comment by tmiw** [comment]
> @tmiw you've put so much work into this! Plus it's spun off other PRs like the windows build system improvements. So I really feel:
> 
> 1. We need to get feedback from visually impaired users before merging.  I'll ping them again.
> 2. Given all the changes it might be useful for regular users to try it too.  I'll do that this week.

Fair enough. I just sent out a new build to you. 👍

**Comment by drowe67** [comment]
Hi @tmiw.  Not sure if I'm doing this right, but I tried using freedv-gui without my mouse for example:
1. Tabbing around the main dialog takes me to all sorts of fields I would never use if I couldn't see, including the the txt box at the bottom which is read-only, and the centre panel tabs
1. Wouldn't we just want Start and Mode radio buttons on the main dialog in the Tab sequence?  Or maybe alt-M for mode.
1. Alt-S stops and starts nicely, that's pretty cool :+1: 
2. How would a blind person set the squelch slider?  Also I wonder if they would need some sort of feedback that we have started ... a sighted user sees the waterfall. 
2. Alt-F takes me to file, but Alt-T doesn't take me to tools. But I can arrow across to tools.
3. On Tools-Audio Config, it takes me to "Input Computer To Radio" first.  Good. As press up/down arrow I get some really big delays on some devices like pulse, and a bunch of stderr ALSA-messages come out.  However maybe that's a Linux thing.  Tabbing from there takes me to the text box for the sound device, not sure if that's useful?  Setting up sound cards is hard for sighted people, this is likely to be a major challenge.
1. I've lost the squelch and Tx level sliders:
   Screenshot from 2021-05-17 08-38-08
   
Anyhoo, like I said, I don't really know how a blind person might use this, so take the points above with a grain of salt!

Another brainstorm - but perhaps a no frills command line version might suit a blind person better.  That would be a significant project though, and would require a lot of buy in from the blind community.  Or, a few more CLI commands on freedv-gui, e.g. to set the sound cards, and Hamlib ptt device might be a neater solution.

Thanks for having a look into this one - I can see it's a real challenge!  I think it's OK to set a fixed scope or timebox on this work. If we just make some incremental improvement and merge, that's still a step in the right direction.  It may not be possible for us to sort out all the issues in a reasonable amount of time (and still be fun).

**Comment by tmiw** [comment]
@drowe67, I was able to confirm the issue with the sliders on Linux and pushed a commit to resolve it. The issue was a side effect of trying to make the UI more adaptable for smaller screens/resolutions (note that if you shrink the vertical space of the window, the side controls will automatically move horizontally to remain visible).

As for your other points, my comments are below. Keep in mind that I used [NVDA](https://www.nvaccess.org/) (open source screen reader) for testing, which seems to be predominantly used on Windows:

> * Tabbing around the main dialog takes me to all sorts of fields I would never use if I couldn't see, including the the txt box at the bottom which is read-only, and the centre panel tabs
> * Wouldn't we just want Start and Mode radio buttons on the main dialog in the Tab sequence?  Or maybe alt-M for mode.

Actually, the text box would be nice to tab to (along with the Clear button). NVDA and other screen readers will read a control if it has focus, so Tab will need to work for whatever we want to be spoken to the user. How common the text field feature of FreeDV is used, though, I'm not sure about.

> * How would a blind person set the squelch slider?  Also I wonder if they would need some sort of feedback that we have started ... a sighted user sees the waterfall.

In my testing, NVDA was able to speak the new slider values when I used the Up and Down keys.

> * Alt-F takes me to file, but Alt-T doesn't take me to tools. But I can arrow across to tools.

Hmm, weird, Alt-T seems to work fine for me here (Ubuntu 20.04) with 46aa504. Not sure what could be going on but I went through and made sure I didn't have Alt-T set twice in the code.

> * On Tools-Audio Config, it takes me to "Input Computer To Radio" first.  Good. As press up/down arrow I get some really big delays on some devices like pulse, and a bunch of stderr ALSA-messages come out.  However maybe that's a Linux thing.  Tabbing from there takes me to the text box for the sound device, not sure if that's useful?  Setting up sound cards is hard for sighted people, this is likely to be a major challenge.

That brings up whether we want that to be an editable field in the first place. Seems like it'd introduce the possibility for users to mess something up, so making it read-only might be a good idea.

**Comment by drowe67** [comment]
> Actually, the text box would be nice to tab to (along with the Clear button). NVDA and other screen readers will read a control if it has focus, so Tab will need to work for whatever we want to be spoken to the user. 

Ahh yes of course - good point :+1 

> In my testing, NVDA was able to speak the new slider values when I used the Up and Down keys.

Nice :+1: 
 
> > * Alt-F takes me to file, but Alt-T doesn't take me to tools. But I can arrow across to tools.

Hah, it's working now.  Must have been a silly error by me.  Sorry!

> That brings up whether we want that to be an editable field in the first place. Seems like it'd introduce the possibility for users to mess something up, so making it read-only might be a good idea.

Agree :slightly_smiling_face:

**Comment by tmiw** [comment]
Although, come to think of it, I'm not sure it's worthwhile to be able to tab to the waterfall, etc. I disabled that with the latest commit.

**Comment by drowe67** [comment]
@tmiw well it's been a week and I haven't heard any more feedback from the visually impaired beta testers.  So just ping me when you're happy with this one and we can merge.

**Comment by tmiw** [comment]
@drowe67, I'm ready to merge. 👍

**Pull request merged**
