### PR TITLE
Building for windows using Docker

### PR DESCRIPTION
**Pull request by drowe67**
1. Using Danilo's fine work to allow us to build freedv-gui for windows using Docker.  This is another step in automating the build process, and allows us to use Docker containers rather than a Fedora machine.  

   Thanks Danilo for showing how this can be done :+1: 

2. Now building working Windows installers, people have tested the EXEs with good results. 

3. Fixed a FIFO size bug that had broken 2020 Rx.

4. Automation script to build freedv-gui on a remote machine and upload 32 and 64 bit Windows installers to a web site in a single step.

### CODE REVIEW

**Comment by srsampson** [comment]
That is on my wish list! Bravo

**Comment by hobbes1069** [comment]
Looks interesting! It doesn't really matter since we're just using the mingw capabilities but technically Fedora 28 is EOL.

**Comment by hogthrob** [comment]
Hi,
changing the Fedora release is a simple matter of changing FED_REL in docker-compose-win.yml to any desired number  and verifying that the build instructions in the docker file fdv_win_fedora/Dockerfile are still working for this release.

**Comment by drowe67** [comment]
Thanks @hobbes1069 @hogthrob I'll try Fedora 30 on the next pass on this code.  certainly makes my life easier - one script to run for the whole build and deploy process.

**Pull request merged**
