### PR TITLE
freedv-gui 1.4.2 release

### PR DESCRIPTION
**Pull request by drowe67**
Bumped version number to 1.4.2 and added some release notes.

Built against [codec2](https://github.com/drowe67/codec2/commit/8bfb6abdd727da6bc45852772cb45d3efc30a8e4) and [LPCNet](https://github.com/drowe67/LPCNet/commit/0a361f1e526d8b11d1904c3dab1cd2baaa84b4eb)

@hobbes1069 - codec2 has been refactored over recent months, so I wanted to get a maintenance release of freedv-gui out there to keep it up to date. If all is well nothing much should change from the point of view of end users.

### CODE REVIEW

**Comment by ra1nb0w** [comment]
I tested the release with the latest wxWidgets 3.1.4 but I get the following error during start:
```
../src/common/sizer.cpp(2128): assert "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed in DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

```
The full error
Screenshot 2020-08-03 at 11 02 30

**Comment by drowe67** [comment]
> I tested the release with the latest wxWidgets 3.1.4 but I get the following error during start:

Thanks for letting me know.  I don't have the time to work on this right now - however if you work out a fix pls let me know.  Seems to run OK on 3.0 on my Ubuntu 18 machine.

**Comment by ra1nb0w** [comment]
on 3.0 it works fine; the fix seems to require many changes to `src/topFrame.cpp` and unfortunately I don't have the time now to do it.

**Comment by drowe67** [comment]
> on 3.0 it works fine; the fix seems to require many changes to `src/topFrame.cpp` and unfortunately I don't have the time now to do it.

Cool - well I'll log it as an issue for now and hopefully someone will attend to it some time.

**Comment by ra1nb0w** [comment]
a side question: do you know why John Melton (g0orx) has removed freedv from his pi/linHPSDR? thank you

**Comment by drowe67** [comment]
> a side question: do you know why John Melton (g0orx) has removed freedv from his pi/linHPSDR? thank you

Nope, have never had any contact with John.

**Comment by ra1nb0w** [comment]
thank you :)

**Pull request merged**
