### PR TITLE
Add band filtering in the FreeDV Reporter dialog

### LINKED ISSUE #470: Add ability to filter on band/frequency in FreeDV Reporter
Per feedback from the digitalvoice list, there should be some sort of way to filter listings in FreeDV Reporter (ideally both in-app and on the website) by band/frequency to make it easier to find contacts. 

Email for context:

> As the number of total FreeDV users increases and more are using the reporter, it might be advantageous to have a band "filter" (toggle-switch) incorporated into the Reporter.
>
> As more users on the west coast for example start using 40 or 75,  the list of callsigns might become a little long if all the other bands are always  included in the list. 
>
> For those using small screen screens such as that on a laptop there's barely enough room for the main window!.
>
> A band filter "button" could allow choosing to display only users on the band of use making it a little easier to see all the users on that band instead of being interspersed with all the other users on different bands.

Questions:

1. Should users be able to show more than one band/frequency at a time, or would the choice be between showing everything and showing only the people on the selected part of the spectrum?
2. How should this present itself to the user (drop-down, checkboxes, etc.)? Can this be different depending on whether it's in-app or the website?

### PR DESCRIPTION
**Pull request by tmiw**
Resolves #470 by adding UI in the FreeDV Reporter dialog to filter the displayed stations by band. This brings the application back into parity with the [FreeDV Reporter website](https://qso.freedv.org/).

### CODE REVIEW

**Comment by barjac** [comment]
Nice! Seems to work just fine in a quick test.
However....
It uses up another line of precious screen height. If it was positioned in line with 'Close' etc. at the bottom it would not.

The filter is not saved/remembered between runs of freedv, it would be good if it was. 
My opinion is that selections not remembered between runs are more to have to set up on each program start.

**Comment by tmiw** [comment]
> Nice! Seems to work just fine in a quick test. However.... It uses up another line of precious screen height. If it was positioned in line with 'Close' etc. at the bottom it would not.
> 
> The filter is not saved/remembered between runs of freedv, it would be good if it was. My opinion is that selections not remembered between runs are more to have to set up on each program start.

Updated on both counts :)

**Comment by barjac** [comment]
New position is fine.
However there are two bugs. :(
1.
Start freedv in All Bands mode. (i.e. last stopped in All Bands)
Start the modem with me (rig) on 60m
I am shown correctly.
Switch FDVR to 60m view and I am shown correctly
Stop the modem and program and restart FDV and the modem and the selector shows 60m but the list is displaying all bands.
Should be showing 60m now.

2.
Start freedv in All Bands mode.
Start the modem with me on 60m
I am shown correctly.
Switch FDVR to 60m and I am shown correctly (so far so good as previous bug)
Stop the modem and restart it
I am still there shown correctly
Switch to 'All Bands' and I am shown twice.
Switch back to 60m view and I am now shown twice there as as well.
This continues to increment the number of duplicates each time the modem is restarted.

**Comment by Tyrbiter** [comment]
> This is with a package built from the ms-reporter-band-filter branch at [28e701b](https://github.com/drowe67/freedv-gui/commit/28e701bb95cfd91caeffa1e1e9b9d3f428aacf40) which I assume is up-to-date with previous fixes in master? Just wondering, as we have had duplicates previously which were fixed.

Seems to have all except the portaudio deprecation commit https://github.com/drowe67/freedv-gui/commit/1e4f014a49c5e8199685d61006b4bd1700bae0a3 from earlier today.

**Comment by tmiw** [comment]
The above bugs should be fixed now 👍

**Comment by barjac** [comment]
https://github.com/drowe67/freedv-gui/pull/490

**Comment by tmiw** [comment]
> #490

Yep, aware that #490 isn't related to this change. Figured it was easier to add it again to this one than to try to reopen that PR.

**Comment by barjac** [comment]
Looks good :)
I will get chance to test on air tomorrow.

**Comment by barjac** [comment]
Another bug ;)
After stopping the modem, changing the reporter band selection causes the reporter to display what I guess is obsolete data for each band (previously viewed?).
Did you ever investigate further making the reporter work whether or not the modem was running?
When I first saw this bug I thought that it had been implemented :)

**Comment by tmiw** [comment]
> Another bug ;) After stopping the modem, changing the reporter band selection causes the reporter to display what I guess is obsolete data for each band (previously viewed?). 

Yep, just pushed a change to fix this.

> Did you ever investigate further making the reporter work whether or not the modem was running? When I first saw this bug I thought that it had been implemented :)

Haven't looked into it as it was pretty low priority. I'm not 100% sure it's a good idea to but we'd have to investigate further.

**Comment by barjac** [comment]
Seems good to go now. :)

**Comment by barjac** [comment]
Just found another :(
Internal reporter thinks 5403.5 kHz is not 60m.
It shows in 'All bands' but not in '60m' on Internal Reporter. It does show in 60m on Web Reporter.

**Comment by Tyrbiter** [comment]
The highest frequency I can find for any 60m allocation worldwide is 5450kHz.

**Comment by tmiw** [comment]
> Just found another :( (While testing Voice keyer cleanup branch) Internal reporter thinks 5403.5 kHz is not 60m. It shows in 'All bands' and 'Other' but not in '60m' on Internal Reporter. It does show in 60m on Web Reporter. In the UK 60m is channelized in 11 varying width sub-bands between 5258.5 and 5406.5.

It actually should be failing to show in the Web-based Reporter as well. From the Web version's JavaScript:

```javascript
freqToBandClass = function(freq) {
    if (freq >= 1800000 && freq <= 2000000)
    {
        return "band-160m";
    }
    else if (freq >= 3500000 && freq <= 4000000)
    {
        return "band-80m";
    }
    else if (freq >= 5351500 && freq <= 5366500)
    {
        return "band-60m";
    }
    ...
```

vs. on C++:

```c++
bool FreeDVReporterDialog::isFiltered_(uint64_t freq)
{
    auto bandForFreq = FilterFrequency::BAND_OTHER;
    
    if (freq >= 1800000 && freq <= 2000000)
    {
        bandForFreq = FilterFrequency::BAND_160M;
    }
    else if (freq >= 3500000 && freq <= 4000000)
    {
        bandForFreq = FilterFrequency::BAND_80M;
    }
    else if (freq >= 5351500 && freq <= 5366500)
    {
        bandForFreq = FilterFrequency::BAND_60M;
    }
    ...
}
```

The original source was from this table on Wikipedia, which is apparently incorrect as [the article about 60 meters](https://en.wikipedia.org/wiki/60-meter_band) does indicate the 5250-5450 KHz range mentioned previously:

Screenshot 2023-08-05 at 8 49 10 AM

Anyway, I'll widen 60 meters in both codebases.

**Comment by barjac** [comment]
https://rsgb.org/main/operating/band-plans/hf/5mhz/
Which agrees with my licence.

**Comment by Tyrbiter** [comment]
> https://rsgb.org/main/operating/band-plans/hf/5mhz/ Which agrees with my licence.

In the UK, and other places, this is what is permitted, but there are other places which permit operation over a wider range of frequencies, there is further information here https://en.wikipedia.org/wiki/60-meter_band some of which is quite surprising:

"Somalia (ITU Region 1): The Somali Ministry of Information & Communication Technology [[79]](https://en.wikipedia.org/wiki/60-meter_band#cite_note-79) permits non-channelized 5 MHz / 60-meter operation. Upper sideband (USB) must be used and the allocation is 5060–5450 kHz. All modes are allowed and the maximum power permitted is 3 kW on a non-interference basis."

So actually perhaps we ought to make the lower limit 5060kHz, although I am not sure that 3kW would not interfere with anything local to the transmitter :-/

**Comment by tmiw** [comment]
I just set it to 5250-5450 for now. We can always change later if needed.

**Comment by Tyrbiter** [comment]
> I just set it to 5250-5450 for now. We can always change later if needed.

Indeed. I have not yet seen an extra strong FreeDV signal from a 6O station :)

**Pull request merged**
