### PR TITLE
Refactor rig control logic

### PR DESCRIPTION
**Pull request by tmiw**
The Hamlib and Serialport classes contain GUI logic and heavy use of synchronous logic, which is not ideal for multiple reasons:

* Potential delays in starting/stopping FreeDV depending on user's system/configuration.
* Increased potential for bugs related to improper use of GUI logic/threading.

This PR creates a new fdv_rig_control library that implements replacements for Serialport and Hamlib that only deal with serial port and Hamlib related tasks. GUI logic formerly inside Hamlib and Serialport is relegated to the respective GUI classes.

TODO:

- [x] Restore previous frequency/mode (Hamlib)
- [x] Test Hamlib support (rig control, PTT)
- [x] (macOS/Linux) Test serial port input/output
- [x] (Windows) Test serial port input/output

### CODE REVIEW

**Comment by Tyrbiter** [comment]
I thought I would try this despite it being WIP, and using build_linux.sh I get a linker error:

[100%] Linking CXX executable freedv
cd /home/bdm/git/freedv-gui-ms-rig-control-refactor/build_linux/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/freedv.dir/link.txt --verbose=1
/usr/lib64/ccache/c++  -Wall -g CMakeFiles/freedv.dir/dlg_audiooptions.cpp.o CMakeFiles/freedv.dir/dlg_easy_setup.cpp.o CMakeFiles/freedv.dir/dlg_filter.cpp.o CMakeFiles/freedv.dir/dlg_options.cpp.o CMakeFiles/freedv.dir/dlg_ptt.cpp.o CMakeFiles/freedv.dir/freedv_reporter.cpp.o CMakeFiles/freedv.dir/main.cpp.o CMakeFiles/freedv.dir/plot.cpp.o CMakeFiles/freedv.dir/plot_scalar.cpp.o CMakeFiles/freedv.dir/plot_scatter.cpp.o CMakeFiles/freedv.dir/plot_spectrum.cpp.o CMakeFiles/freedv.dir/plot_waterfall.cpp.o CMakeFiles/freedv.dir/topFrame.cpp.o CMakeFiles/freedv.dir/sox_biquad.c.o CMakeFiles/freedv.dir/util.cpp.o CMakeFiles/freedv.dir/eq.cpp.o CMakeFiles/freedv.dir/voicekeyer.cpp.o CMakeFiles/freedv.dir/playrec.cpp.o CMakeFiles/freedv.dir/ongui.cpp.o CMakeFiles/freedv.dir/freedv_interface.cpp.o -o freedv  -Wl,-rpath,/home/bdm/git/freedv-gui-ms-rig-control-refactor/codec2/build_linux/src:/home/bdm/git/freedv-gui-ms-rig-control-refactor/LPCNet/build_linux/src: audio/libfdv_audio.a pipeline/libfdv_audio_pipeline.a config/libfdv_config.a gui/util/libfdv_gui_util.a reporting/libfdv_reporting.a rig_control/libfdv_rig_control.a sox/libfdv_sox.a util/libfdv_util.a /home/bdm/git/freedv-gui-ms-rig-control-refactor/codec2/build_linux/src/libcodec2.so.1.1 /usr/lib64/libpulse.so /usr/lib64/libhamlib.so ../sioclient_build/libsioclient.a /usr/lib64/libsamplerate.so /usr/lib64/libsndfile.so /usr/lib64/libspeexdsp.so /usr/lib64/libdl.a ../_deps/wxwidgets-build/lib/libwx_gtk3u_core-3.2.a ../_deps/wxwidgets-build/lib/libwx_baseu-3.2.a ../_deps/wxwidgets-build/lib/libwx_gtk3u_aui-3.2.a ../_deps/wxwidgets-build/lib/libwx_gtk3u_html-3.2.a ../_deps/wxwidgets-build/lib/libwx_baseu_net-3.2.a ../_deps/wxwidgets-build/lib/libwx_gtk3u_adv-3.2.a ../_deps/wxwidgets-build/lib/libwx_gtk3u_propgrid-3.2.a /home/bdm/git/freedv-gui-ms-rig-control-refactor/LPCNet/build_linux/src/liblpcnetfreedv.so.0.5 -lm /usr/lib64/libcurl.so ../_deps/wxwidgets-build/lib/libwx_gtk3u_core-3.2.a ../_deps/wxwidgets-build/lib/libwxpng-3.2.a ../_deps/wxwidgets-build/lib/libwxtiff-3.2.a ../_deps/wxwidgets-build/lib/libwxjpeg-3.2.a -lnotify ../_deps/wxwidgets-build/lib/libwx_baseu-3.2.a ../_deps/wxwidgets-build/lib/libwxzlib-3.2.a ../_deps/wxwidgets-build/lib/libwxregexu-3.2.a -lsecret-1 -ldl -lgtk-3 -lgdk-3 -lz -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lharfbuzz -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lcairo -lglib-2.0 -lgobject-2.0 /usr/lib64/libSM.so /usr/lib64/libICE.so /usr/lib64/libX11.so /usr/lib64/libXext.so /usr/lib64/libXtst.so /usr/lib64/libgnomevfs-2.so 
/usr/bin/ld: ../_deps/wxwidgets-build/lib/libwx_gtk3u_core-3.2.a(imagpng.cpp.o): undefined reference to symbol 'png_get_pHYs@@PNG16_0'
/usr/bin/ld: /usr/lib64/libpng16.so.16: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/freedv.dir/build.make:439: src/freedv] Error 1
make[2]: Leaving directory '/home/bdm/git/freedv-gui-ms-rig-control-refactor/build_linux'
make[1]: *** [CMakeFiles/Makefile2:1448: src/CMakeFiles/freedv.dir/all] Error 2
make[1]: Leaving directory '/home/bdm/git/freedv-gui-ms-rig-control-refactor/build_linux'
make: *** [Makefile:156: all] Error 2

I have both libpng-devel and libpng12-devel installed. Possibly the same problem where using the non-system wxWidgets is falling over something non-obvious.

Just thought you'd like to know.

**Comment by tmiw** [comment]
> Fedora spec file build method completed, so it's probably something about the options used in wxWidgets. One suggestion to fix this sort of problem is to enable less restrictive search by the linker using:
> 
> export LDFLAGS="-Wl,--copy-dt-needed-entries"
> 
> not sure exactly where this could be added to the build_linux.sh script or one of the cmake files.

I just tried build_linux.sh on the absolute latest Fedora 39 (with both wxGTK and wxGTK-devel installed) and this branch built with no problem. Same thing if I let the build process build its own version of wxWidgets. I'm not sure why you're getting this error but I remember it was something specific to the RPM build process. /shrug

Anyway, this PR should be good to go on the hamlib side. Serial PTT still needs to be tested/fixed as needed but once you can get it built, it should work fine for most.

**Comment by Tyrbiter** [comment]
> > Fedora spec file build method completed, so it's probably something about the options used in wxWidgets. One suggestion to fix this sort of problem is to enable less restrictive search by the linker using:
> > export LDFLAGS="-Wl,--copy-dt-needed-entries"
> > not sure exactly where this could be added to the build_linux.sh script or one of the cmake files.
> 
> I just tried build_linux.sh on the absolute latest Fedora 39 (with both wxGTK and wxGTK-devel installed) and this branch built with no problem. Same thing if I let the build process build its own version of wxWidgets. I'm not sure why you're getting this error but I remember it was something specific to the RPM build process. /shrug
> 

The RPM build actually worked, it was somewhere in building wxWidgets using the build_linux.sh script that failed, probably because the linker didn't look in the right include files for some reason.

> Anyway, this PR should be good to go on the hamlib side. Serial PTT still needs to be tested/fixed as needed but once you can get it built, it should work fine for most.

I might have a try with this new code, it should be easy to revert to the current devel version if I have any problems.

**Comment by tmiw** [comment]
@Tyrbiter, @barjac: I did some more testing on multiple OSes and I'm fairly confident that this PR works okay now on all the valid PTT/CAT methods (footswitch/PTT input, serial port PTT output and Hamlib). Let me know if you guys run into any issues. 👍

**Comment by barjac** [comment]
> @Tyrbiter, @barjac: I did some more testing on multiple OSes and I'm fairly confident that this PR works okay now on all the valid PTT/CAT methods (footswitch/PTT input, serial port PTT output and Hamlib). Let me know if you guys run into any issues. 👍

I will but can't test immediately as my wife is coming out of hospital today.
As long as this has not broken anything related to rigctld usage as this is the only way I use hamlib. ;)

**Comment by Tyrbiter** [comment]
I have built and am testing with this as the latest commit:

https://github.com/drowe67/freedv-gui/pull/564/commits/a136cbc5db38ee5f685ccc3b3edb42a237b26964

however the changes in this commit:

https://github.com/drowe67/freedv-gui/pull/564/commits/3c132eea6a933057d0f6540232d6e4ebddbea6bf

don't appear to store and recall the freq/mode on the radio when starting the modem.

**Comment by barjac** [comment]
I tested a136cbc and it seems fine with rigctld.
Stopping the modem, changing the rig frequency and re-starting the modem does cause FreeDV to get the new frequency OK.

**Comment by tmiw** [comment]
> I have built and am testing with this as the latest commit:
> 
> [a136cbc](https://github.com/drowe67/freedv-gui/commit/a136cbc5db38ee5f685ccc3b3edb42a237b26964)
> 
> however the changes in this commit:
> 
> [3c132ee](https://github.com/drowe67/freedv-gui/commit/3c132eea6a933057d0f6540232d6e4ebddbea6bf)
> 
> don't appear to store and recall the freq/mode on the radio when starting the modem.

Fixed in [19884f6](https://github.com/drowe67/freedv-gui/pull/564/commits/19884f6751db24b7762b96283404da890cee06a3).

**Comment by Tyrbiter** [comment]
> >don't appear to store and recall the freq/mode on the radio when starting the modem.
> 
> Fixed in [19884f6](https://github.com/drowe67/freedv-gui/pull/564/commits/19884f6751db24b7762b96283404da890cee06a3).

OK, so now the mode is being set on modem start then unset back to what it was, however the frequency is staying at the previous frequency not to the setting in the drop down list, it remains the same on modem stop.

**Comment by tmiw** [comment]
> > > don't appear to store and recall the freq/mode on the radio when starting the modem.
> > 
> > 
> > Fixed in [19884f6](https://github.com/drowe67/freedv-gui/pull/564/commits/19884f6751db24b7762b96283404da890cee06a3).
> 
> OK, so now the mode is being set on modem start then unset back to what it was, however the frequency is staying at the previous frequency not to the setting in the drop down list, it remains the same on modem stop.

I think I see what you're talking about. Hopefully 6ec04f6 resolves the issue for you. 👍

**Pull request merged**
