### PR TITLE
Improve labeling of PTT/CAT control options.

### PR DESCRIPTION
**Pull request by tmiw**
Improves labeling of CAT control/Hamlib related options based on feedback in #539:

1. Rename "PTT Config" to "CAT and PTT Config" in the Tools menu:

Screenshot 2023-09-20 at 10 20 59 PM

2. Change title of PTT Config dialog and change checkbox for Hamlib to clarify that it also handles CAT control (along with PTT):

Screenshot 2023-09-20 at 10 21 03 PM

### CODE REVIEW

**Comment by tmiw** [comment]
> When setting up a RX only system there is no 'None' option for 'PTT Uses:' which is very confusing. Maybe that box should be greyed when audio settings for TX are none. Although when an install is occasionally used for both RX only and TX, I think that the TX audio settings should stay and have a 'enable TX' check box somewhere to avoid constantly changing the TX audio configs. WDYT?

I think it might be confusing to gray out that setting if there are no transmit sound devices set. (The user could very well be setting Hamlib settings first, before audio devices.) Also, most people don't need to change that setting, anyway; it's there for the oddball radios that don't have working CAT support for PTT.

> It would be sensible to have this covered by the enhancement request for #417 multiple reloadable settings.

The labeling changes in this PR, or did you mean consolidating the config dialogs?

**Comment by Tyrbiter** [comment]
> > It would be sensible to have this covered by the enhancement request for #417 multiple reloadable settings.
> 
> The labeling changes in this PR, or did you mean consolidating the config dialogs?

I was referring to @barjac comments on the issue with Rx only, confusion with config settings etc. If it is possible to create a PR for the  https://github.com/drowe67/freedv-gui/issues/417 enhancement then it would mean only doing the work once.

It seemed to me to be sensible to have templates of some kind for this, creating a new config would allow the selection of a Tx/Rx one, or Rx only. Additional templates could be added if needed. I realise that this is quite a big task, the wsjtx Configurations menu has been around a while, maybe something like it would give us a decent UI for this.

**Comment by tmiw** [comment]
> I was referring to @barjac comments on the issue with Rx only, confusion with config settings etc. If it is possible to create a PR for the #417 enhancement then it would mean only doing the work once.
> 
> It seemed to me to be sensible to have templates of some kind for this, creating a new config would allow the selection of a Tx/Rx one, or Rx only. Additional templates could be added if needed. I realise that this is quite a big task, the wsjtx Configurations menu has been around a while, maybe something like it would give us a decent UI for this.

I think if we were to do any consolidation, Easy Setup would likely get rolled into Tools->Options, with the existing PTT and audio device settings still accessible via their respective Advanced buttons. That would still be a lot of work and I'd like to do some refactoring and other cleanup first before attempting.

**Comment by Tyrbiter** [comment]
Yes, I wasn't suggesting that you should just dive in and hack everything about.

Thought required, and you have clearly already done some thinking about it.

**Comment by barjac** [comment]
> I think it might be confusing to gray out that setting if there are no transmit sound devices set. (The user could very well be setting Hamlib settings first, before audio devices.) Also, most people don't need to change that setting, anyway; it's there for the oddball radios that don't have working CAT support for PTT.

OK understood , so could there be a 'none' option in the list?
I have scratched my head looking at this setting while setting up a system with no transmit.
It's asking for something impossible as no option is applicable.

> > It would be sensible to have this covered by the enhancement request for #417 multiple reloadable settings.

Yes but it still needs to make sense.

**Comment by tmiw** [comment]
> OK understood , so could there be a 'none' option in the list? I have scratched my head looking at this setting while setting up a system with no transmit. It's asking for something impossible as no option is applicable.

The typical way of setting up a RX only station is to not specify any TX sound devices, but adding None probably won't hurt: https://github.com/drowe67/freedv-gui/pull/556

**Comment by barjac** [comment]
Not had chance to check fully but selecting 'None' seems to be a switch from transceive to receive only mode without needing to touch the audio settings.
If I have the above correct then it's a nice feature but not labelled as such.
It would be hard to find without reading docs and who does that? ;)
I really think that the feature needs a separate 'Receive Only' check box maybe above the 'PTT Uses:' (or somewhere else entirely) that when enabled greys out 'PTT Uses:'.

**Comment by Tyrbiter** [comment]
@tmiw mentioned it in this PR

https://github.com/drowe67/freedv-gui/pull/556

**Comment by tmiw** [comment]
What about renaming "None" to "None (RX Only)" in that drop-down?

But yeah, the user manual could probably be improved in general. not just when talking about this feature. PRs to update it are welcome :)

**Pull request merged**
