### PR TITLE
Revert #116

### PR DESCRIPTION
**Pull request by drowe67**
Attempting rollback of https://github.com/drowe67/freedv-gui/pull/116 until we've worked on it a little more.

### CODE REVIEW

**Comment by drowe67** [comment]
hi @tmiw could you pls take a quick look at this and confirm it rolls back #116?  Its builds and runs OK.

**Comment by tmiw** [comment]
Currently building, will let you know how it goes.

**Comment by tmiw** [comment]
@drowe67, I'm currently testing this build and it's not obviously broken. 

Unfortunately, it looks like we will need to resolve the issue in some manner. I'll email a sample WebSDR recording and explain what I mean.

**Comment by drowe67** [comment]
> @drowe67, I'm currently testing this build and it's not obviously broken.

OK, I'll merge this.

> Unfortunately, it looks like we will need to resolve the issue in some manner. I'll email a sample WebSDR recording and explain what I mean.

Cool.  Maybe I can try to repeat here with a WebSDR. Happy to work with you to resolve the issue :+1:

**Pull request merged**
